### ISSUE TITLE
Analyze if we can remove jupyter in favor of artifactory

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#100]
### What is the expected enhancement?

As we are doing with [redis](https://github.com/Qiskit-Extensions/quantum-serverless/pull/95) and [ray](https://github.com/Qiskit-Extensions/quantum-serverless/issues/99) let's see if we can remove our jupyter dependency in favor of artifactory.

**Comment by Tansito** [comment]
This issue finished to be harder than expected. After an in depth research we discovered that there is no an official `jupyter` chart for k8s but an official `jupyter-hub` chart. 

Their preferred system for k8s is the jupyterhub, that's why they only support that. They have a project for smaller projects called "[the littlest jupyter hub](https://tljh.jupyter.org/en/latest/)" but is in beta and by now the don't have support for helm.

Luckly the documentation to [setup](https://z2jh.jupyter.org/en/stable/jupyterhub/customizing/extending-jupyterhub.html#extending-jupyterhub) and [optimize](https://z2jh.jupyter.org/en/stable/administrator/optimization.html#optimization) jupyterhub seems really good. But it's true that the migration is not as easy as install the dependency and apply some changes in the configuration. That's the mains reason because we decide to put this issue `on-hold` and discuss when will be the best moment to recover it.

**Comment by Tansito** [comment]
From last discussions we decided to drop support from `helm` for `jupyter`. Now we only support `jupyter` in development environment with `docker-compose` to facilitate the development. So, closing this issue following last decisions.

**Comment by psschwei** [comment]
> From last discussions we decided to drop support from `helm` for `jupyter`. Now we only support `jupyter` in development environment with `docker-compose` to facilitate the development. 

Should we drop the notebook image from the CI build jobs too?

**Comment by Tansito** [comment]
> Should we drop the notebook image from the CI build jobs too?

We didn't drop it totally because it's working but to be honest I don't see a reason to have it. In my opinion we could drop it to simplify configurations. @pacomf , @IceKhan13 opinions?

**Comment by IceKhan13** [comment]
I'm in favour of dropping notebooks support, but If we will drop jupyter we need to rework all quickstart docs

**Comment by psschwei** [comment]
> ... need to rework all quickstart docs

yeah, maybe we just leave it alone then... :laughing:

**Comment by Tansito** [comment]
> I'm in favour of dropping notebooks support, but If we will drop jupyter we need to rework all quickstart docs

I see... It's a good side-effect. It didn't come to my mind when we were commenting this. Probably we will need some time to think a better way to handle this 🤔
