### ISSUE TITLE
Log user ID with job ID in scheduler logs

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#1026]
### What is the expected enhancement?

The scheduler logs currently show the job ID when the job is scheduled / status changes. However, it would be helpful to also log the user ID associated with the job, either when the job starts executing

https://github.com/Qiskit-Extensions/quantum-serverless/blob/c205da62a9e0815f8876b959e0d873c31832d5a7/gateway/api/management/commands/schedule_queued_jobs.py#L106

and/or when the job status is updated

https://github.com/Qiskit-Extensions/quantum-serverless/blob/c205da62a9e0815f8876b959e0d873c31832d5a7/gateway/api/management/commands/update_jobs_statuses.py#L44

**Comment by akihikokuroda** [comment]
Closing as done by #1083
