### ISSUE TITLE
Job in status QUEUED even if it is running

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#1030]
### Steps to reproduce the problem
Run a program.

### What is the current behavior?
Job in status QUEUED even if it is running.
All other state working correctly.

### What is the expected behavior?
Job should change to status running when running

**Comment by akihikokuroda** [comment]
I can not make this happen.  Is there any way or conditions that I can make this happen? @IceKhan13

**Comment by akihikokuroda** [comment]
Oh, I see it now.

**Comment by psschwei** [comment]
Have we still been seeing this behavior (we've done 4-5 releases since this was reported)? If so, do we have a way to replicate it?

**Comment by Tansito** [comment]
No answers and I couldn't replicate it in all the tests that I did since this was opened so I think it's worth it to close it.
