### ISSUE TITLE
Expose ability to set min/max number of workers per cluster

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#1031]
### What is the expected behavior?

Expose ability to set min/max number of workers per cluster.

Requirements:
- Defaults should be configurable in gateway. 
- Min and max should have verification rules in gateway, so user would not be able to set crazy numbers (positive integers within boundaries).

From client it should look something along those lines:
```python
job = serverless.run(
  program,
  config=Configuration(
    workers=[Worker(2, 4)] # 2 cpu, 4 GB mem
  )
)
```

**Comment by akihikokuroda** [comment]
It' not clear for me this configuration. 
```
  config=Configuration(
    workers=[Worker(2, 4)] # 2 cpu, 4 GB mem
  )
```
This should specify 

- min/max number of workers.  
- enable/disable autoscaling
- number of workers when the autoscaling is disabled
- cpu and mem resource of a worker

How about this way?
```
  config=Configuration(
    autoscale_enable=False
    workers=4
    worker_cpu=2
    worker_mem=4
  )
  config=Configuration(
    autoscale_enable=True
    min_workers=1
    max_workers=4
    worker_cpu=2
    worker_mem=4
  )
```

**Comment by akihikokuroda** [comment]
closing as done by #1085
