### ISSUE TITLE
some images for v0.6.4 are not available  

### ISSUE THREAD

**Issue by akihikokuroda** [Qiskit-Extensions/quantum-serverless#1037]
### Steps to reproduce the problem
ICR | build and push action failed for v0.6.4

https://github.com/Qiskit-Extensions/quantum-serverless/actions/runs/6434979718
### What is the current behavior?
CI build failed

### What is the expected behavior?
CI should not fail

**Comment by psschwei** [comment]
looks like there's problems with the dependencies :cry:

**Comment by IceKhan13** [comment]
looks like there is no `matplotlib==3.8.0` for python 3.8

**Comment by psschwei** [comment]
do we have folks using python 3.8? or could we limit support to 3.9+?

**Comment by BajajSmriti** [comment]
Local infrastructure setup-
`docker compose --profile jupyter up`
Error response from daemon: manifest for icr.io/quantum-public/quantum-serverless-gateway:0.6.4 not found: manifest unknown: manifest unknown
Same is occurring for 0.6.5

**Comment by psschwei** [comment]
If we cut a new version once #1045 merges, we _should_ be back on track with all images existing.

We may also want to look into the release process and see if we can update those jobs to keep running on failure, so in a worst case it we'd still have all the other times (i.e. the python 3.9 ones wouldn't get squeezed out)
