### ISSUE TITLE
Job completed status should match that of Qiskit

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit-Extensions/quantum-serverless#1039]
### What is the expected enhancement?
Currently a completed job has the status `'SUCCEEDED'` where as the rest of Qiskit uses `'DONE'`: https://qiskit.org/documentation/stable/0.37/stubs/qiskit.providers.JobStatus.html

It would be nice to be uniform here.

**Comment by nonhermitian** [comment]
Same is true for the error state of a job

**Comment by IceKhan13** [comment]
xref: https://github.com/Qiskit-Extensions/quantum-serverless/issues/684
