### ISSUE TITLE
Job logs should be updated as the code is executed

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit-Extensions/quantum-serverless#1040]
### What is the expected behavior?

Currently the the job logs do not update until a program is finished.  This means one cannot track the progress of a function as it goes through its steps.  As functions can get arbitrarily long, it would be nice to be able to rack the status of them as they go through.

**Comment by IceKhan13** [comment]
ref: 
https://github.com/Qiskit-Extensions/quantum-serverless/blob/9a56a13d53405b2bdbbeb7a654d903de8f76f443/gateway/api/management/commands/update_jobs_statuses.py#L56

Need to update logs on each poll
