### ISSUE TITLE
Add a Provider.save_account method

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/quantum-serverless#1042]
### What is the expected enhancement?
Users should be able to save/load their provider tokens to/from their local environment. This allows them to more easily instantiate their serverless provider in their code. The interface should likely be similar to other IBM interfaces, such as Qiskit Runtime [IBMProvider.save_account](https://qiskit.org/ecosystem/ibm-provider/stubs/qiskit_ibm_provider.IBMProvider.save_account.html#qiskit_ibm_provider.IBMProvider.save_account).

Outstanding questions:
- Should this method be included in the `BaseProvider` class, or should only some providers implement it?
    - Only IBMServerlessProvider

**Comment by IceKhan13** [comment]
Only IBMServerlessProvider
