### ISSUE TITLE
CI: helm linter fails

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#1065]
### Steps to reproduce the problem

https://github.com/Qiskit-Extensions/quantum-serverless/actions/runs/6707371529/job/18263819172

### What is the current behavior?

Helm linter github action fails

### What is the expected behavior?

Helm linter action should work

**Comment by psschwei** [comment]
![image](https://github.com/Qiskit-Extensions/quantum-serverless/assets/44698588/3d7ce215-2c2e-4b0c-b382-ee07d7335ebb)

So we're using cosign for verification, but we can't verify cosign ... :laughing:

**Comment by psschwei** [comment]
Fixed in #1070 and #1071
