### ISSUE TITLE
Files download: support for h5 and other popular formats.

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#1113]
### What is the expected enhancement?

Currently we only support `tar` files download. Users requested for more file types support. 

We at least need to support `h5` and maybe other formats.

**Comment by akihikokuroda** [comment]
The current implementation seems:
The `file_upload`/`file_download` work with any file extensions.  The `files` api list only the files with extentsion `tar`.
Am I correct?  If so, we just need to add additional file extension in the `files` api.
