### ISSUE TITLE
`qiskit.opflow` is deprecated 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit-Extensions/quantum-serverless#1130]
`qiskit.opflow` was deprecated in Qiskit 0.43 (with terra 0.24, released in May 2023) and will be removed in the coming version major Qiskit release 1.0 (planned for early 2024)

> The `qiskit.opflow` module is deprecated and will be removed no earlier
> than 3 months after the release date. For code migration guidelines,
> visit https://qisk.it/opflow_migration.

In the short term, you could readjust your deps `qiskit>=0.45.0,<1`. In the long term, you should stop using `qiskit.opflow` before mid 2024. The `QiskitPartner` documentation also uses `qiskit.opflow`: https://github.com/Qiskit-Extensions/quantum-serverless/tree/main/docs/examples/source_files

And consider removing the `filterwarnings`:
https://github.com/Qiskit-Extensions/quantum-serverless/blob/main/client/pyproject.toml#L6

**Comment by psschwei** [comment]
Looks like we're just using opflow in the VQE / QAOA examples 

https://github.com/search?q=repo%3AQiskit-Extensions%2Fquantum-serverless%20opflow&type=code

xref: #1095

**Comment by akihikokuroda** [comment]
Yes, we have to.  VQE is import it but not using it.

**Comment by akihikokuroda** [comment]
QAOA is not using opflow, either.  I'll take the reference (import) out.
