### ISSUE TITLE
Gateway: invalid subdomain for user cluster if name is not valid

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#1133]
### Steps to reproduce the problem

Username with special characters (like `_`).

### What is the current behavior?

 it is not valid name for subdomain and cluster creation will fail. 

### What is the expected behavior?

Cluster should be created and username should not affect that

**Comment by psschwei** [comment]
One thing to note is that the job itself did not error... I could see the error in the scheduler logs, but `job.status()` showed the job was `QUEUED` ... though maybe it would've eventually failed if I waited longer

**Comment by Tansito** [comment]
Yes, the timeout should put later on the job as failed if I remember correctly.
