### ISSUE TITLE
Run tests using LocalProvider

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#1141]
### What is the expected enhancement?

Now that we have `LocalProvider`, we should make that the default environment for running tests in the CI. Specifically, https://github.com/Qiskit-Extensions/quantum-serverless/blob/main/.github/workflows/docker-build.yaml could be updated to just run the notebooks (rather than docker build, etc.)

In theory, this means we could also drop docker compose. Longer-term though, we still need full e2e testing on Kubernetes (xref https://github.com/Qiskit-Extensions/quantum-serverless/issues/117#issuecomment-1594718083).

**Comment by psschwei** [comment]
In the interim, will note that `docs/getting_started/basic/01_running_program.ipynb` works fine using `LocalProvider`

**Comment by akihikokuroda** [comment]
All notebook samples are using the `ServerlessProvider` now.  Should they be updated to use the `LocalProvider` in the docs or just modified during the tests on the fly?
