### ISSUE TITLE
annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#1158]
### Steps to reproduce the problem

Deploy serverless helm chart on k8s 1.28+

### What is the current behavior?

Get warning: `annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead`

### What is the expected behavior?

No warning

---

To fix, we need to replace the annotation with the spec. Here's the locations the annotation shows up as of the time of opening this issue:

https://github.com/search?q=repo%3AQiskit-Extensions%2Fquantum-serverless%20ingress.class&type=code

**Comment by karlaspuldaro** [comment]
Hello! I would like to take a look at this issue, @psschwei can you assign this to me pls?
(btw, I'm new to the project)

**Comment by psschwei** [comment]
Thanks @karlaspuldaro !
