### ISSUE TITLE
Gateway: add swagger / openapi docs

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#1165]
### What is the expected enhancement?

Add swagger and openapi docs for gateway and document everything related to that API.

Epic https://github.com/Qiskit-Extensions/quantum-serverless/issues/1164

**Comment by david-alber** [comment]
hi @IceKhan13 are you on this already? 
If still available, I would love to give it a shot to learn more about gateway APIs.

**Comment by IceKhan13** [comment]
Hey @david-alber ! Sure, take it away! and let us know if you need anything

**Comment by IceKhan13** [comment]
ref https://drf-yasg.readthedocs.io/en/stable/readme.html#openapi-3-0-note
