### ISSUE TITLE
Gateway: add ability to share functions / programs

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#1167]
### What is the expected behavior?

Add ability to share serverless programs. 

At this point adding `public` flag would be enough. But once fined-grained access will be added, we can consider sharing with specific groups only.

**Comment by psschwei** [comment]
By share we mean "share with everyone" and not something more fine-grained (i.e. share with group A), right?

**Comment by akihikokuroda** [comment]
So for now, is adding a BooleanField to the Program class enough?

**Comment by psschwei** [comment]
My thought was that, if the public flag was set, the gateway would call the catalog API under the hood to upload the program, under the assumption that all shared functions would go through the catalog. That might not be the best assumption though (we can discuss more later today).

I also worry a bit about security -- letting anyone specify a function as public opens a number of cans of worms...
