### ISSUE TITLE
Include test automatization for helm

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#117]
### What is the expected enhancement?

I would like to introduce test in our helm configuration to ensure overall that with new changes the configuration continues working.

**Comment by Tansito** [comment]
Some resources that I found:
- [How to test helm charts?](https://rokpoto.com/test-helm-charts/)
- [Advanced test practices for helm charts](https://medium.com/@zelldon91/advanced-test-practices-for-helm-charts-587caeeb4cb)
- [Automated testing with terratest](https://blog.gruntwork.io/automated-testing-for-kubernetes-and-helm-charts-using-terratest-a4ddc4e67344)

And a summary from these resources that I liked:

1. run [helm lint](https://helm.sh/docs/helm/helm_lint/)
2. run [helm template](https://helm.sh/docs/helm/helm_template/)
3. validate the template using [kubeconform](https://github.com/yannh/kubeconform)
4. run [helm unittest](https://github.com/helm-unittest/helm-unittest)

Apart from the `unittest` I could make progressions with `kubeconform` running the next command:
```sh
 helm template --release-name quantum-serverless --values values.yaml . | kubeconform --summary --skip RayCluster
```

I needed to skip `RayCluster` to avoid the error: 
```
 RayCluster quantum-serverless-kuberay failed validation: could not find schema for RayCluster
```

I think this is a good starting point to start building a github action for CI but I would like to confirm with Paul this initiative once time he returns.

**Comment by psschwei** [comment]
One of the Helm maintainers recommends this one: https://github.com/helm/chart-testing
There's also an example project with demos: https://github.com/helm/charts-repo-actions-demo

I _think_ I like the helm one, because they already have the actions written and they have a release check too, but I don't have a super strong opinion here and could easily be persuaded otherwise :smile:

**Comment by Tansito** [comment]
Thanks @psschwei I will take a look more in depth but it looks really good 🙏 .

**Comment by psschwei** [comment]
We should also have an e2e test using helm (spin up kind, install via helm, run the sample notebooks). 

That should probably be done as part of the existing docker e2e test so we aren't building the images multiple times

**Comment by Tansito** [comment]
@psschwei I will start working on this today. By now I will review all the information that we collected here so let me know if you found something more 😄
