### ISSUE TITLE
Gateway / repository: add catalog api

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#1170]
### What is the expected enhancement?

Add catalog rest api.
Add documentation.

Epic https://github.com/Qiskit-Extensions/quantum-serverless/issues/1168

**Comment by psschwei** [comment]
Initial thoughts on methods:

* Add function to catalog
* List functions in catalog (filter by tag?)
* delete function from catalog

need to think about an access model for add/delete...

**Comment by akihikokuroda** [comment]
> Add function to catalog

Is this publish the function in the `Program`?  If so, is the function have to be uploaded first and marked as `public`?

**Comment by IceKhan13** [comment]
> List functions in catalog (filter by tag?)

I think text search also a good option

**Comment by IceKhan13** [comment]
> need to think about an access model for add/delete...

We have `IsOwner` access model, which allows only owners to modify (delete) object 

https://github.com/Qiskit-Extensions/quantum-serverless/blob/e839c7726f4a95042cb1cd45b270bcf2189a4d81/gateway/api/permissions.py#L6

Need to think about adding entries.

**Comment by akihikokuroda** [comment]
The ModelViewSet provides these.
```
POST:api/v1/catalogentry/ - create
GET:api/v1/catalogentry/ - list
GET:api/v1/catalogentry/{id}/ - get
UPDATE:api/v1/catalogentry/{id}/ - update
PATCH:api/v1/catalogentry/{id}/ - partial update
DELETE:api/v1/catalogentry/{id}/ - delete
```
Is it good enough to add the query string to the list api to filter by tag, description and title?
The create, update, partial update and delete are only allowed for the owner of the program.

**Comment by psschwei** [comment]
> How about add `add_catalog` API to the `Program` API like below?

minor nit on naming: maybe `to_catalog` or something along those lines... add catalog sounds likes we're adding a catalog, not adding to the catalog...

**Comment by akihikokuroda** [comment]
completed in #1204
