### ISSUE TITLE
Docs: jupyter example notebooks fix

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#1174]
### Steps to reproduce the problem

In docs we suggest to use docker compose with jupyter examples. When you run docker compose it is failing with 
```
manifest for [icr.io/quantum-public/quantum-serverless-notebook:0.8.2-py39](http://icr.io/quantum-public/quantum-serverless-notebook:0.8.2-py39) not found
```

### What is the current behavior?

Docker compose fails

### What is the expected behavior?

Docs and compose should not point to non-existing jupyter notebook example anymore

**Comment by akihikokuroda** [comment]
Is this because we don't build the image any longer?

**Comment by IceKhan13** [comment]
yes, we should remove any mention about jupyter notebooks from docs and docker compose

**Comment by psschwei** [comment]
And eventually we'll sunset the docker compose entirely as the docs move to IQP (:crossed_fingers: :smile: )

**Comment by psschwei** [comment]
I can go ahead and clean this up in our existing docs

**Comment by IceKhan13** [comment]
Thank you!

**Comment by johannesgreiner** [comment]
@psschwei @IceKhan13 et al, the repo readme still recommends jupyter notebooks as standard path. Worth a separate cleanup?

**Comment by johannesgreiner** [comment]
@psschwei @IceKhan13 in https://qiskit-extensions.github.io/quantum-serverless/deployment/local.html in Step 4, is the recommendation to use Jupyter Lab obsolete?

> To create and run programs in this simulated cluster, we recommend using [Jupyter Lab](https://jupyter.org/install).

**Comment by psschwei** [comment]
> @psschwei @IceKhan13 et al, the repo readme still recommends jupyter notebooks as standard path. Worth a separate cleanup?

Yes, the main readme also needs an update (missed it on the PR).


> @psschwei @IceKhan13 in https://qiskit-extensions.github.io/quantum-serverless/deployment/local.html in Step 4, is the recommendation to use Jupyter Lab obsolete?
> 
> > To create and run programs in this simulated cluster, we recommend using [Jupyter Lab](https://jupyter.org/install).

Jupyter Lab is still recommended, we just aren't providing a containerized environment. Instead, folks should manage their own (we probably should also include something about using a virtual environment a la `venv` in that section too...)
