### ISSUE TITLE
broken link in deployment docs

### ISSUE THREAD

**Issue by johannesgreiner** [Qiskit-Extensions/quantum-serverless#1182]
https://qiskit-extensions.github.io/quantum-serverless/deployment/cloud.html#installation-requirements points to https://github.com/Qiskit-Extensions/quantum-serverless/tree/main/infrastructure#tools which doesn't exist

> Important: before you download the above packages, check the [versions listed in our Github](https://github.com/Qiskit-Extensions/quantum-serverless/tree/main/infrastructure#tools) of each tool to ensure that you download a compatible version.

**Comment by psschwei** [comment]
Good catch -- looks like that page disappeared a while ago. We should probably drop that link
