### ISSUE TITLE
Helm Chart: Ingress Class annotation deprecated

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#1187]
### What is the expected enhancement?

Our helm chart currently specifies the ingress class via an annotation, but that annotation has been deprecated in favor of `.spec.ingressClassName`. We should update to use this new value.

**Comment by psschwei** [comment]
https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation

**Comment by Tansito** [comment]
@psschwei is this not a duplicate of #1158

**Comment by psschwei** [comment]
Yes it is :smile:
