### ISSUE TITLE
Gateway: add public flag to `CatalogEntry` 

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#1210]
### What is the expected enhancement?

Add public flag to catalog entry and show only public (and self authored) entries in GET views.

**Comment by akihikokuroda** [comment]
The catalog can be created for the **public** program.  For the catalog, do we need category of the catalog instead of just a boolean flag?

**Comment by akihikokuroda** [comment]
I'm thinking about adding a choice field.  For now, the choices are [PRIVATE, COMMUNITY, CERTIFIED].  WDYT?

**Comment by psschwei** [comment]
It's a bit unclear to me what aspects of program uploading / sharing are being handled by the gateway API and what ones via the catalog API.

Should we consider only letting the user upload private programs via the gateway, and all shared uploads (whether full public or subgroups) are done via the catalog? 

Maybe do a mini design session on the scopes at our next dev call ?

**Comment by IceKhan13** [comment]
> Maybe do a mini design session on the scopes at our next dev call ?

Sounds good. Added to our agenda!
