### ISSUE TITLE
Update issue template to include Security vulnerability type

### ISSUE THREAD

**Issue by karlaspuldaro** [Qiskit-Extensions/quantum-serverless#1213]
### What is the expected enhancement?
The [contribution guidelines doc](https://github.com/Qiskit-Extensions/quantum-serverless/blob/main/CONTRIBUTING.md#opening-issues) mentions 4 types of issues one can open:
1. Bug reports
2. Enhancement request
3. Feature request
4. Security vulnerability

Although when opening a new issue there is no Security vulnerability type:
<img src="https://github.com/Qiskit-Extensions/quantum-serverless/assets/25207344/e7662970-416b-4756-a8b6-1684be810082" width="400">

Updating the template to include the missing type would keep it the consistent with the docs.
For this type of issue, it could also be helpful to add relevant context items to the template (eg. OS, main dependencies version, etc). 
Would it make sense to also offer some secure way of contacting the project team with sensitive reports if needed?

**Comment by psschwei** [comment]
Security vulnerabilities shouldn't be reported publicly... we should remove that from the contribution docs and create a new issue to add a proper security policy (Qiskit for examples allows reporting via the Security tab on the repo, assuming there's no cost involved that's probably what we should do)

cc @Tansito

**Comment by Tansito** [comment]
Totally agree, @psschwei 👍

**Comment by psschwei** [comment]
I enabled reporting a vulnerability on the repo.... we just need to add a `SECURITY.md` with how to report (we can probably use https://github.com/Qiskit/qiskit/blob/main/SECURITY.md as a model)... @karlaspuldaro do you want to open a PR for that?

**Comment by karlaspuldaro** [comment]
@psschwei Yes I can! Should I open a new issue for that or update this one?

**Comment by psschwei** [comment]
I think using this one's fine

**Comment by karlaspuldaro** [comment]
@psschwei Cool, can you assign this issue to me please?

**Comment by Tansito** [comment]
Done @karlaspuldaro 😄
