### ISSUE TITLE
Make docs Qiskit 1.0.0 compatible

### ISSUE THREAD

**Issue by david-alber** [Qiskit-Extensions/quantum-serverless#1224]
### Steps to reproduce the problem
See #1205 

### What is the current behavior?
PR checks (Notebook LocalProvider, Test QS on Kubernetes) fail when testing the execution of `docs/getting_started/basic/*.ipynb` files with the error: 
```
ImportError: Qiskit is installed in an invalid environment that has both Qiskit >=1.0 and an earlier version.
You should create a new virtual environment, and ensure that you do not mix dependencies between
Qiskit <1.0 and >=1.0. Any packages that depend on 'qiskit-terra' are not compatible with Qiskit 1.0 and
will need to be updated. Qiskit unfortunately cannot enforce this requirement during environment resolution.
See https://qisk.it/packaging-1-0 for more details.
``` 

Note: Qiskit 1.0.0 has been released on 15.Feb.2024, [see](https://pypi.org/project/qiskit/#history).

### What is the expected behavior?
The .ipynb files are executed without import error and pass the PR checks.

**Comment by david-alber** [comment]
As this is related to #1205 I am happy to take it 😃.

**Comment by Tansito** [comment]
I assigned the issue to you @david-alber , let me know if you need help. And thank you so much to take it ❤️

**Comment by david-alber** [comment]
Thanks @Tansito. I am on it :).
