### ISSUE TITLE
Use JSON standar for all our calls to the gateway

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#1268]
### Steps to reproduce the problem

Right now from client we are not specifying the format of the `Request` to the `Gateway` what it's generating a `QueryDict` and not a standard JSON in the `Request` type. This generates in the `serializers` not expected behaviors.

We should use in all our requests from `Client` the json format. Ref: https://requests.readthedocs.io/en/latest/user/quickstart/#more-complicated-post-requests

This can generate extra modifications in the Gateway if any end-point fails due to the change in the format (special attention in the serializers).

**Comment by akihikokuroda** [comment]
The QueryDict seems that the `QueryDict` is the default post data format in [django HttpRequest](https://docs.djangoproject.com/en/5.0/ref/request-response/#django.http.HttpRequest.POST).  It may not be good to change it to JSON.

**Comment by Tansito** [comment]
I'm not proposing to change django's HTTPRequest POST. I'm proposing to send a standard JSON `requests` from python `client` what basically will do is setup a `Content-Type: application/json` and it's what we can expect that almost all of our clients will do if we have other clients (like the future catalog, for example).

**Comment by akihikokuroda** [comment]
Our python client is sending requests to the gateway endpoint that is expecting django's HTTPRequest, right?   So it is expecting QueryDict data.  I agree the typical client uses `Content-Type: application/json`.  Are you proposing to change the gateway endpoint to accept `Content-Type: application/json`?

**Comment by Tansito** [comment]
Not exactly, let me explain it better. I think our current `gateway` accepts `Content-Type: application/json`. What I'm proposing is change the request that we are sending from client:

Current call: https://github.com/Qiskit-Extensions/quantum-serverless/blob/bcd01d0690fb8d29423cd401ee0910824259451a/client/quantum_serverless/core/job.py#L436

From what I saw this request doesn't send a: `Content-Type: application/json`. To do that we need to apply this change: https://requests.readthedocs.io/en/latest/user/quickstart/#more-complicated-post-requests

```python
                    request=lambda: requests.post(
                        url=url,
                        **json**=data,
                        files={"artifact": file},
                        headers={"Authorization": f"Bearer {self._token}"},
                        timeout=REQUESTS_TIMEOUT,
                    ),
```

That basically is change `data` to `json`. And automatically it seems (because I didn't test it in-depth) that with that change `requests` setup the correct `Content-type`. I think that in our gateway we are not going to need to do any change, but not 100% sure.

**Comment by akihikokuroda** [comment]
I tried `json=data` and `json=json.dumps(data)` but the gateway couldn't handle them.

**Comment by Tansito** [comment]
I didn't discard that we need to review our serializers configuration. This change can affect them.

**Comment by akihikokuroda** [comment]
I looked into a little more.  The python `requests` doesn't support the `Content-type: application/json` when the request has `files`.  When the `reqeusts.post` has `files`, it ignores the `json` completely.
https://github.com/psf/requests/blob/f1bb07d39b74d6444e333879f8b8a3d9dd4d2311/src/requests/models.py#L555

When the `reqeusts.post` has `files` and `data, the main `Content-type` is `multipart/form-data` and each `form-data` doesn't have the `Content-type`.

So we can use `Content-type: application/json` for `run_existing` but not for `upload` or `run`.

**Comment by Tansito** [comment]
Yep, that's what I was expecting. And in those cases what are we using for `Content-type`, Aki?

**Comment by akihikokuroda** [comment]
`Content-type` is `multipart/form-data` for `POST` requests with `files`.  If `data` are not None, the `data` are sent as parts of the multipart. If `json` is not None, the `json` is just ignored and not to sent at all.

**Comment by Tansito** [comment]
Perfect, I think it's fair to say that we should use when we can `Content-type: application/json` and for those exceptions the `Content-type: multipart/form-data`. Does it sound reasonable?

**Comment by akihikokuroda** [comment]
Actually I change to the Context_type to json for `run_existing` in #1285
