### ISSUE TITLE
Add version endpoint to gateway API

### ISSUE THREAD

**Issue by akihikokuroda** [Qiskit-Extensions/quantum-serverless#1277]
### What is the expected enhancement?

Provide a new API endpoint to return the version of the quantum-serverless.

**Comment by akihikokuroda** [comment]
Is it good idea to put the version constant in the main/settings.py and return it as the `/version` api response?  Any opinion? @Tansito @IceKhan13 @psschwei

**Comment by Tansito** [comment]
Yeah, my idea would be to set an environment variable with the version. Version by now is more than enough.

**Comment by psschwei** [comment]
Would it be possible to use that envvar to set the version in all the other various places (such as the image tag)? In an ideal world we wouldn't add another place we have to update when changing versions :smile:

**Comment by Tansito** [comment]
yep, totally

**Comment by akihikokuroda** [comment]
I'll add a global helm variable like this:
```
# ===================
# Quantum Serverless Info
# ===================
global:
  version: v0.9.0
```

So any component that needs version can access it.
