### ISSUE TITLE
Infrastructure: keycloak helm

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#136]
### What is the expected behavior?

Include optional keycloak chart to quantumserverless helm chart. 

Reference PR https://github.com/Qiskit-Extensions/quantum-serverless/pull/135

Epic https://github.com/Qiskit-Extensions/quantum-serverless/issues/105

**Comment by akihikokuroda** [comment]
The helm chart is here.  https://github.com/codecentric/helm-charts/tree/master/charts/keycloak. I'll put it and configure the values.yaml file

**Comment by IceKhan13** [comment]
There is also an instance of bitnami chart for Keycloak https://bitnami.com/stack/keycloak/helm
Not sure which one is better to use 🤔 It is up to you 😄

**Comment by akihikokuroda** [comment]
@IceKhan13 I'll take a look at both.  Tnanks!
