### ISSUE TITLE
API server auth

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#138]
### What is the expected behavior?

Add authentication to KubeRay API server.

As API server is a simple HTTP endpoint we can probably reuse same sidecar proxy here too https://github.com/Qiskit-Extensions/quantum-serverless/issues/137

Epic https://github.com/Qiskit-Extensions/quantum-serverless/issues/105

**Comment by akihikokuroda** [comment]
The kuberay api-server helm chart doesn't have a hook for the side car container.  It is not managed by any operator so the deployment can be patched during install for now.  I'll work to create a PR in the kuberay repo to add the hook into the helm chart.

**Comment by akihikokuroda** [comment]
I created a PR updating the helm chart of the apiserver for the sidecar in Kuberay. https://github.com/ray-project/kuberay/pull/920

**Comment by akihikokuroda** [comment]
I'm going to enable "Client Credentials Grant" in OAuth2 specification for the apiserver.
