### ISSUE TITLE
Repository: project dockerization

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#152]
### What is the expected enhancement?

Dockerize the project to simplify installation and setup.

Epic #112

**Comment by maximilien** [comment]
Nice, I'd like to try this. Anyone else working on this issue?

Also, is there a suggested base image?

**Comment by maximilien** [comment]
If there's a base image for python / ray that I should use please let me know otherwise I'll start with UBI and add to it. Thx

**Comment by IceKhan13** [comment]
you are our hero @maximilien !

Repository image will be standalone and only required to have packages under[ requirements.txt](https://github.com/Qiskit-Extensions/quantum-serverless/blob/repository-project/repository/requirements.txt)

Assigned to you. I think some version of alpine-python or ubuntu is fine as it has everything that we might possibly need.  

--- 

For ray nodes we are using base ray image already with client + qiskit installed, so we are covered there

**Comment by maximilien** [comment]
Perfect. Thanks @IceKhan13

**Comment by Tansito** [comment]
How are you going with this issue @maximilien ? It's one of the key points for #151 , if you couldn't have the time to look at it I can take it and add you as reviewer once time I have it.

**Comment by akihikokuroda** [comment]
@Tansito @maximilien I'm looking at #105.  I'm thinking that I can integrate keycloak to the repository at pod level (with the sidecar container) instead of the Django level.  If it's OK and you don't mind, I want to work on this and #157 as well as #105.  Thanks!

**Comment by Tansito** [comment]
Not problem from my part @akihikokuroda go ahead, thank you! 🙏

**Comment by akihikokuroda** [comment]
@IceKhan13 I see.  The sidecar probably doesn't work for it.  So it is not simply controlling access to the API.  The user information must be passed to the API logic and processed.  Right?

**Comment by Tansito** [comment]
Yeah, you need a system that maps in some way the users. Our initial proposal was to use a middleware to use the logic from keycloak and manage there the user but I don't know if you have other proposals to that.

**Comment by akihikokuroda** [comment]
No, I don't.  I'll work in the direction.  Thanks!

**Comment by IceKhan13** [comment]
closed in #238
