### ISSUE TITLE
Keycloack integration for repository authentication

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#153]
### What is the expected enhancement?

We want to integrate keycloack authentication process with our users managed by the repository project.

Epic: #112

**Comment by IceKhan13** [comment]
Some references:
- https://www.informaticsmatters.com/blog/2021/06/01/installing-keycloak-on-Django-rest-framework.html
- https://blog.jonharrington.org/static/integrate-django-with-keycloak
- https://sairamkrish.medium.com/keycloak-integration-part-3-integration-with-python-django-backend-5dac3b4a8e4e

**Comment by akihikokuroda** [comment]
I'm looking for a Django keycloak library that is not under GPL.

**Comment by IceKhan13** [comment]
Closing for now
