### ISSUE TITLE
Add documentation on using redis, jaeger as external services, helm charts.

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#160]
### What is the expected enhancement?

Add documentation on using redis, jaeger.

Related to https://github.com/Qiskit-Extensions/quantum-serverless/pull/146

Epic https://github.com/Qiskit-Extensions/quantum-serverless/issues/139

**Comment by maximilien** [comment]
Can you elaborate on this a bit more? Do you mean documenting on how to use Jaeger for the same results as #146?

**Comment by IceKhan13** [comment]
We are putting it on hold for now until we will have jaeger helm chart. It will be a part of https://github.com/Qiskit-Extensions/quantum-serverless/issues/139 epic. 

Idea here is to document how to enable installation of jaeger./redis/ etc and what those projects are and why we need them (how do we use them). For example redis is for kv store and jaeger to trace requests and metrics through system.

**Comment by IceKhan13** [comment]
No longer needed
