### ISSUE TITLE
Update Kuberay service selector after install

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#167]
Part of #55 

We need to update the selector for the kuberay api-server after it is installed in order for it to be accessible.

By default, the service for the Kuberay api-server uses the selector `app.kubernetes.io/name: kuberay-apiserver`. However, the quantum-serverless install results in the following label block on the pod:

```yaml
labels:
    app.kubernetes.io/component: kuberay-apiserver
    app.kubernetes.io/name: quantum-serverless
```

I'm assuming there's some logic that overwrites the existing `app...name` label and adds the quantum-serverless one, but I haven't taken the time to try and find it yet.

If we update the selector to use `app.kubernetes.io/component: kuberay-apiserver` instead (i.e. use the `component` label instead of the `name` one), then we're fine.

There's two options:

* include a `patch` command in the install instructions to update the selector. This should be fairly straightfoward, though would add an extra set to the setup.
* update the helm install logic to use the appropriate label. This is probably more involved, though as I haven't looked at the code yet, not sure how much.

@IceKhan13 what are your thoughts?

**Comment by IceKhan13** [comment]
I also haven't looked at it in details, but I think selector should use `component` instead of name. Probably it's just a small mistake by kuberay team. We can have PR to kuberay chart that fixes this.  Or have a patch. 

Anyway name should be arbitrary and selector should not be for hardcoded name.

**Comment by psschwei** [comment]
Sounds good. For now I'm going to patch manually to get the provider work done, then will open an issue/PR against kuberay to get the fix in.

**Comment by psschwei** [comment]
@akihikokuroda fixed this in https://github.com/ray-project/kuberay/pull/918
