### ISSUE TITLE
Client: investigate pylint warnings

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#180]
### What is the current behavior?

From #178 we reported some weird pylint warnings.

### What is the expected behavior?

Investigate how to fix / remove them.

**Comment by psschwei** [comment]
Here's the warnings:

```
lint: commands[1]> pylint -rn quantum_serverless tests

------------------------------------
Your code has been rated at 10.00/10

pylint: Command line or configuration file:1: UserWarning: Specifying exception names in the overgeneral-exceptions 
option without module name is deprecated and support for it will be removed in pylint 3.0. Use fully qualified name 
(maybe 'builtins.BaseException' ?) instead.
pylint: Command line or configuration file:1: UserWarning: Specifying exception names in the overgeneral-exceptions 
option without module name is deprecated and support for it will be removed in pylint 3.0. Use fully qualified name 
(maybe 'builtins.Exception' ?) instead.
```

FWIW, they don't appear to be blocking, as I saw these even in a [passing test](https://github.com/Qiskit-Extensions/quantum-serverless/actions/runs/4129507631/jobs/7135180946)...

**Comment by Tansito** [comment]
Thanks @psschwei ! About the priority agree, I marked it as `priority: low` just to have it in the radar and not forget it.
