### ISSUE TITLE
Improve filter implementation

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#220]
### What is the expected enhancement?

From #162 we agreed to improve the current filter implementation using [DjangoFilterBackend](https://www.django-rest-framework.org/api-guide/filtering/#djangofilterbackend) as we described in [this comment](https://github.com/Qiskit-Extensions/quantum-serverless/pull/164#discussion_r1109698443).

**Comment by IceKhan13** [comment]
Closing repository related issue for now. Will reopen with new epics.
