### ISSUE TITLE
Bootstrap time from lunching job to actual job execution

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#244]
### What is the expected behavior?

Metrics: bootstrap time from lunching job to actual job execution. 

Metrics:
- job launch time
- boostrap time between tasks
- optional: cluster node launch
- optional: cluster launch

**Comment by psschwei** [comment]
I think this is something that could be done with [OpenTelemetry](https://opentelemetry.io/docs/instrumentation/python/getting-started/). I'll take a run at getting that implemented and generating metrics.

**Comment by psschwei** [comment]
Thinking out loud, I wonder if we can just grep this info from the logs... :thinking:

**Comment by IceKhan13** [comment]
I think once we will have OT traces it will be resolved automatically. Log parsing not worth it IMO :)

**Comment by psschwei** [comment]
Yeah, I was wondering if we could get it before I implement OT... :chicken: vs :egg:

**Comment by IceKhan13** [comment]
should be available in OT
