### ISSUE TITLE
Keycloak does not play nicely with Kind

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#246]
This came up in #189 ... simplest solution is to use something other than Kind locally (e.g. minikube / docker desktop) if you can, but ideally setup should work for kind too, so...

### Steps to reproduce the problem

Spin up a kind cluster, i.e. `kind create cluster`

Do the usual `helm install`, but the local-ip for connecting to keycloak is not easily found

### What is the current behavior?

Depending on your system, there could be a bunch of network interfaces listed, and the user has to basically try each one until one (hopefully) works

### What is the expected behavior?

The IP would be easily discoverable, either a single IP ala minikube (`minikube ip`) or an easily identifiable service

**Comment by akihikokuroda** [comment]
@psschwei How do you access to the service (like Ray dashboard) in the kind cluster from the host system?

**Comment by psschwei** [comment]
either by creating a node port or using kubectl port-forward

**Comment by akihikokuroda** [comment]
After `helm install`, some pods don't come up.
```
aaaaa-kuberay-head-hpj87                                          0/2     Pending   0             74m
``` 
The status is 
```
    message: '0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are
      available: 1 No preemption victims found for incoming pod.'
```
Do they come out  for you @psschwei 
Thanks!

**Comment by psschwei** [comment]
They all come up for me... are you running in a VM or somewhere where you have to provide a set amount of resources? (I've seen similar things happen on action runners and minikube where the environment is constrained)

**Comment by akihikokuroda** [comment]
I'm running it in an IBM cloud instance.  Are you using your local system?

**Comment by akihikokuroda** [comment]
It's a small one **2 vCPU | 4 GB**. Kind works fine for the operator development but it may not be enough for this.  I'll try making it bigger.

**Comment by psschwei** [comment]
yeah I think you'll need to bump it up (if I remember right, I needed at least 4 cpus to run QS on minikube)

**Comment by akihikokuroda** [comment]
I increased number of cpu to 4.  Now it's complaining about memory :-). I'll increase it.

BTW, would you try these?
```
docker exec -it kind-control-plane bash
apt-get update
apt-get install net-tools
ifconfig
```
You may see something like this:
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.0.2  netmask 255.255.0.0  broadcast 172.18.255.255
        inet6 fc00:f853:ccd:e793::2  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::42:acff:fe12:2  prefixlen 64  scopeid 0x20<link>
        ether 02:42:ac:12:00:02  txqueuelen 0  (Ethernet)
        RX packets 82454  bytes 1574518816 (1.5 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 54765  bytes 4444950 (4.4 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
I think that the `172.18.0.2` is the address we need.
Thanks!

**Comment by psschwei** [comment]
Saw the same IP, but didn't work for me:

[2023/03/01 19:09:43] [main.go:60] ERROR: Failed to initialise OAuth2 Proxy: error intiailising provider: could not create provider data: error building OIDC ProviderVerifier: could not get verifier builder: error while discovery OIDC configuration: failed to discover OIDC configuration: error performing request: Get "http://172.18.0.2:31059/realms/quantumserverless/.well-known/openid-configuration": dial tcp 172.18.0.2:31059: connect: connection refused

**Comment by akihikokuroda** [comment]
Is the keycloak pod up?  It takes long time to come up.  The head node pod can not wait until it comes up.  If the keycloak is up now.  Would you delete the head node pod?  It restarts the new head node pod and should connect.

Thanks!

**Comment by psschwei** [comment]
Ok, all the pods are up now without errors...

http://localhost/ still doesn't work for me though (though that doesn't seem to be specific to kind)

**Comment by akihikokuroda** [comment]
localhost doesn't work for kind.  Please try http://172.18.0.2/

**Comment by psschwei** [comment]
Nope, that one doesn't work either

**Comment by psschwei** [comment]
ok, making progress... if I use the external IP of the `quantum-serverless-nginx-ingress-controller` service (which for me is `172.18.255.1`) then I see the keycloak login screen... 

however, after logging in it tries to go to `http://localhost/oauth2/callback?<key/values>`, which also fails...

**Comment by psschwei** [comment]
Using an IP instead of localhost results in an `Invalid parameter: redirect_uri` error after clicking the "sign in with keycloak" button

**Comment by akihikokuroda** [comment]
Sorry for mess :-(  
Can you login to the keycloak console?  it should be at http://172.18.0.2:31059/.  You can change the `Valid redirect URIs` value to `http://172.18.0.2/oauth2/callback` by 

1. login to console admin/passw0rd
2. Select 'quantumserverless' in the realm dropdown (should be `master` when you login)
3. select `clients` then `rayclient`
4. `Valid redirect URIs` should be there.

**Comment by psschwei** [comment]
Still the same issue

https://user-images.githubusercontent.com/44698588/222270132-2a7bf655-34cf-4878-b366-a15c2bc90003.mp4

**Comment by akihikokuroda** [comment]
Would you clear cache, history, cookie, etc or using a private (incognito) window?

**Comment by psschwei** [comment]
same thing with a private window in both Firefox and Chrome

**Comment by Tansito** [comment]
Sorry @akihikokuroda , @psschwei yesterday I couldn't have time to read your comments. I was working in the deployment of the project in IBM Cloud and I discovered some missconfigurations that we had (some of them mentioned by you). I'm going to open a PR fixing some of them and maybe we can discuss there too those things.

**Comment by psschwei** [comment]
> replace
> 
> ```
> redirect-url=http://localhost/oauth2/callback
> ```

So I did a little digging, and it looks like Docker Desktop resolves `localhost` to the LoadBalancer service (based on section 2 of [this blog post](https://www.docker.com/blog/how-kubernetes-works-under-the-hood-with-docker-desktop/)). Hopefully it's just as simple as making an update to `/etc/hosts` at runtime (runtime since we can't know what the service IP will be before it's created :sigh:)

**Comment by psschwei** [comment]
Was able to get it working using these steps running against #258 :

* `kind create cluster`
* edit `values.yaml` to change the `redirection-url` to `localhost:8880`
* install via helm
* `kubectl port-forward -n ray svc/quantum-serverless-nginx-ingress-controller 8880:80`
* open `localhost:8880` in the browser
* login
* success!

![image](https://user-images.githubusercontent.com/44698588/224398810-21de2b30-ab39-4ebc-ba8d-8e61ffacb8c9.png)
