### ISSUE TITLE
User groups

### ISSUE THREAD

**Issue by pacomf** [Qiskit-Extensions/quantum-serverless#253]
### What is the expected behavior?

We should have 3 levels to share programs stored in the repository between users.

1) Programs just available for owners
2) Programs available for everyone
3) Programs available for a set of users that we call user group

By default, we should assume that the option is 1), where the user that upload the program is the only one that can access to it.

An optional parameter will be send in the creation and update endpoints for programs to enable options 2) and 3).

In the option 3) the user group will be a new model that store a set of user_id, where the user group will human identified by a name set by the creator of the group and anyone can create user groups sending the list of user_id. The user group will be just used to share programs. Later we can consider more advanced options about who can create groups (by roles), etc. But for the initial feature, just basic behavior to iterate later depending of the needs discovered after to receive feedback.

**Comment by IceKhan13** [comment]
Closing repository related issue for now. Will reopen with new epics.
