### ISSUE TITLE
Grafana dashboards

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#278]
### What is the expected behavior?

Implement and import grafana dashbaords for system monitoring

Epic https://github.com/Qiskit-Extensions/quantum-serverless/issues/139

**Comment by psschwei** [comment]
Do we have specific metrics we want to build dashboards for? 

The prometheus chart includes dashboards for the k8s system, but we don't have anything specific for Ray metrics... maybe to start with just something simple, like number of jobs?

**Comment by IceKhan13** [comment]
We are also interested in number of tasks in jobs, resources (requested vs avaiable), etc. But number of jobs would be a good start.

**Comment by IceKhan13** [comment]
Ray exposes a lot of metrics! https://docs.ray.io/en/latest/ray-observability/ray-metrics.html#system-metrics

We can even think to include some programmable metrics inside decorators and programs. But this is way-way far away in this moment
