### ISSUE TITLE
Install logging aggregator into the system (Loki)

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#281]
### What is the expected behavior?

Install logging aggregator into the system:
- helm chart
- docker-compose

Epic https://github.com/Qiskit-Extensions/quantum-serverless/issues/174

**Comment by akihikokuroda** [comment]
Loki is under AGPL 3.0.  Is it OK to use?  Do we need some level of separation?

**Comment by psschwei** [comment]
Just ran across this, but the Ray docs have a section on logging for Kubernetes: https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/logging.html

**Comment by akihikokuroda** [comment]
@psschwei Thanks! I'll take a look.
