### ISSUE TITLE
Improve project configuration

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#289]
### What is the expected enhancement?

Once time #151 is merged the project will be officially ready to be deployed. There are some improvements that we can do though, not needed in the first version but interesting to have:
- `.pylint.rc`
- `setup.py`
- `setup.cfg`
- `pyproject.toml`

**Comment by IceKhan13** [comment]
Closing repository related issue for now. Will reopen with new epics.
