### ISSUE TITLE
Should we drop sidecars when keycloak is disabled?

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#291]
We have a switch in the helm chart to [disable Keycloak](https://github.com/Qiskit-Extensions/quantum-serverless/blob/76802c15d9350b1777ab117c28f40b616e21f818/infrastructure/helm/quantumserverless/values.yaml#L236). However, when `keycloakEnabled: false`, the sidecar pods are still installed (for example, on the kuberay head pod). I'm wondering if we should drop the sidecar pods if a user disables keycloak?

**Comment by akihikokuroda** [comment]
We probably should provide some easy way to turn off authentication.   The user can delete the sidecar in the values.yaml 
 for the Ray head node and the APIserver but we need to add some config to disable it in the repository server.

**Comment by akihikokuroda** [comment]
Keycloak can not be disabled at least for now.  The gateway is using it for its authorization.

**Comment by Tansito** [comment]
@psschwei @akihikokuroda I think we can start closing this issue, from the last updates sidecars are not being used and we have other methods to authenticate users too, how do you see it?

**Comment by psschwei** [comment]
Agree, sidecars were dropped in https://github.com/Qiskit-Extensions/quantum-serverless/commit/8d93196369901c9bf734c6ac47a6c7bf1d9ff3f5 so nothing to see here anymore
