### ISSUE TITLE
Image for repository does not exist

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#292]
### Steps to reproduce the problem

Deploy on kubernetes via helm

### What is the current behavior?

$ k get po -n ray quantum-serverless-repository-796588bfcb-8xprv -o json | jq '.spec.containers[].image'
"qiskit/quantum-repository-server:latest"

$ k get po -n ray quantum-serverless-repository-796588bfcb-8xprv 
NAME                                             READY   STATUS             RESTARTS   AGE
quantum-serverless-repository-796588bfcb-8xprv   0/1     ImagePullBackOff   0          3m50s

$ k get events -n ray | grep repository
6m1s        Normal    Scheduled               pod/quantum-serverless-repository-796588bfcb-8xprv                                 Successfully assigned ray/quantum-serverless-repository-796588bfcb-8xprv to kind-control-plane
57s         Warning   DNSConfigForming        pod/quantum-serverless-repository-796588bfcb-8xprv                                 Search Line limits were exceeded, some search paths have been omitted, the applied search line is: ray.svc.cluster.local svc.cluster.local cluster.local ibmuc.com ibmmodules.com s81c.com
4m3s        Normal    Pulling                 pod/quantum-serverless-repository-796588bfcb-8xprv                                 Pulling image "qiskit/quantum-repository-server:latest"
3m37s       Warning   Failed                  pod/quantum-serverless-repository-796588bfcb-8xprv                                 Failed to pull image "qiskit/quantum-repository-server:latest": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/qiskit/quantum-repository-server:latest": failed to resolve reference "docker.io/qiskit/quantum-repository-server:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
3m37s       Warning   Failed                  pod/quantum-serverless-repository-796588bfcb-8xprv                                 Error: ErrImagePull
3m13s       Normal    BackOff                 pod/quantum-serverless-repository-796588bfcb-8xprv                                 Back-off pulling image "qiskit/quantum-repository-server:latest"
3m13s       Warning   Failed                  pod/quantum-serverless-repository-796588bfcb-8xprv                                 Error: ImagePullBackOff
6m1s        Normal    SuccessfulCreate        replicaset/quantum-serverless-repository-796588bfcb                                Created pod: quantum-serverless-repository-796588bfcb-8xprv
6m1s        Normal    ScalingReplicaSet       deployment/quantum-serverless-repository                                           Scaled up replica set quantum-serverless-repository-796588bfcb to 1

Also, https://hub.docker.com/r/qiskit/quantum-serverless-repository returns a 404

### What is the expected behavior?

Image deploys normally

**Comment by akihikokuroda** [comment]
If I understand the actions correctly, the push to the docker hub happens when the release is cut or every night.  The action hasn't executed since the repository-project was merged into the main.  It should be pushed tonight.

**Comment by psschwei** [comment]
ah, good point (didn't realize that just merged today)

**Comment by Tansito** [comment]
oh, this is good point out @akihikokuroda , thank you

**Comment by psschwei** [comment]
Somewhat related (though this might be more for the Qiskit team) is whether the recent [Docker announcement](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/) impacts the repo for our images...

**Comment by akihikokuroda** [comment]
Action failed last night https://github.com/Qiskit-Extensions/quantum-serverless/actions/runs/4443247011/jobs/7800325511
I'll take a look.

**Comment by IceKhan13** [comment]
Good point. We will cut release tomorrow with `repository` and possibly `gateway`

**Comment by akihikokuroda** [comment]
#328 fix this.
