### ISSUE TITLE
Migrate off DockerHub

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#298]
We want to store our images in a different repository than Dockerhub, due to some of the licensing changes that have been made. More details to follow.

Steps to complete:
* [x] #544 
* [x] #553 
* [x] #568 
* [x] Delete DockerHub images

**Comment by pacomf** [comment]
Related with #306

**Comment by pacomf** [comment]
Agree with ICR

**Comment by psschwei** [comment]
Latest release and latest tag images are available on ICR:

<img width="781" alt="image" src="https://github.com/Qiskit-Extensions/quantum-serverless/assets/44698588/288bc175-890f-48d3-885f-4c4eb134cd1b">
