### ISSUE TITLE
Migrate off Docker

### ISSUE THREAD

**Issue by pacomf** [Qiskit-Extensions/quantum-serverless#306]
### What is the expected behavior?

We need to have an alternative to run in local without use docker images and the docker desktop app. Propose some alternatives and evaluate the best one to follow the best standard possible. (@psschwei has some ideas).

Some of the alternatives can be:

- Podman (https://podman.io/) -> Supported by RedHat
- LXD (https://ubuntu.com/lxd) ->  Maintained by Canonical
- Containerd (https://containerd.io/) ->  CNCF-graduated container

**Comment by psschwei** [comment]
giant PLUS ONE to this

**Comment by akihikokuroda** [comment]
On my Mac, my setup is:

- Containerd (replacement for docker engine/daemon)
- nerdctl (replacement for docker CLI)
- Rancher Desktop (replacement for DockerDesktop)

**Comment by Tansito** [comment]
I'm a bit newbie on these environments so I will read your comments and learn 😂

**Comment by psschwei** [comment]
Building images:

Most tools out there require docker / podman, so not sure how much sense it makes to drop Dockerfiles at this point in time. If we really, really want to eliminate all docker tooling, podman probably makes the most sense, BUT podman uses cri-o rather than containerd as the runtime. Not a blocker, but just something to keep in mind.

Running images:

@akihikokuroda has a good solution for running images locally, using rancher.

**Comment by akihikokuroda** [comment]
I'm using Rancher Desktop : It supports Linux, Windows, Mac (both x86 and Apple chips). It runs on the containerd with nerdctl.  nerdctl is almost compatible with docker CLI (it supports Docker compose, too)

FYI: https://www.youtube.com/watch?v=evWPib0iNgY

**Comment by pacomf** [comment]
I agree with use docker engine (with rancher, podman or whatever... just we need to consider the more generic and faster way for run in local), but we need to have some script or similar to run everything from scratch by you... so in 1 command (running the script) anyone can have running the stack in local in any architecture (Apple chip, Intel, etc)... makes sense for you @psschwei ? can we do it?

**Comment by psschwei** [comment]
in theory, yes .... at a minimum, we could detect the user's arch and then find/replace image tags based on that

**Comment by Tansito** [comment]
From what I know if we just declare the image as (just to put an example):

```
FROM nginx:stable-alpine3.17-slim
```

It should build the correct architecture (if the image supports it, of course). We are not adding the `SHA` because that way we would be specifying the arch but, I'm finding it a bit unnecessary lately.

**Comment by psschwei** [comment]
Lima + Kubeadm may also be a good option here, especially for Macs: https://github.com/lima-vm/lima/blob/master/examples/k8s.yaml

**Comment by psschwei** [comment]
Or Colima:
https://github.com/abiosoft/colima

**Comment by psschwei** [comment]
Colima seems like the most straight forward for Mac users:

```
brew install colima
brew install docker
colima start
docker compose ...
```

and for kubernetes
```
colima start --kubernetes
```
or even possibly just
```
kind start cluster
```
