### ISSUE TITLE
Improve Dockerfile configuration for gateway

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#311]
### What is the expected enhancement?

The current Dockerfile configuration that we are using has some differences from our current Dockerfiles. The idea es review it and sync it with the rest of images configuration of the project.

**Comment by psschwei** [comment]
Assuming this would also mean moving it to the `infrastructure/docker/` directory

**Comment by Tansito** [comment]
Correct, @psschwei ! I would appreciate help on these items if you have time 🙏

**Comment by Tansito** [comment]
I will start working on this. Reviewing the tutorials I saw some problems building this image so I will take a look.
