### ISSUE TITLE
Migrate NestedProgram fields to JSONFields

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#314]
### What is the expected enhancement?

NestedProgram has some fields configured as `TextFields` instead of `JSONFields`. The idea is migrate the fields to that specific fields to manage the JSON in an easier way. The specific fields that are going to be change are:
- `arguments`
- `env_vars`
- `dependencies`

**Comment by akihikokuroda** [comment]
I'm not sure if I understand this correctly.  The fields are now 
```
    env_vars: Optional[Dict[str, str]] = None
    dependencies: Optional[List[str]] = None
```
Is this issue still valid?

**Comment by Tansito** [comment]
Nope, probably fixed in some pull request. Thank you, Aki!
