### ISSUE TITLE
Configure API projects to use Postgres

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#315]
### What is the expected enhancement?

To simplify the process for `repository` and for `gateway` we started the MVP's using SQLite. Preparing the projects for production we would like to configure Postgres as the database to use.

**Comment by akihikokuroda** [comment]
I'll try this one.

**Comment by IceKhan13** [comment]
Thank you @akihikokuroda !

**Comment by Tansito** [comment]
Thank you @akihikokuroda ! In case you want some inspiration I was reading some entries to prepare for production the applications:

- https://dragonprogrammer.com/django-drf-api-production-docker/

**Comment by akihikokuroda** [comment]
@Tansito I'll take a look.  Thanks!
