### ISSUE TITLE
Gateway chart improve configuration

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#326]
### What is the expected enhancement?

Currently we have configuration for gateway through env variables.

Some of them can be derived from chart values, like ray host

https://github.com/Qiskit-Extensions/quantum-serverless/blob/a98068912427586fa4162dec6734fe9ce072c507/infrastructure/helm/quantumserverless/charts/gateway/templates/deployment.yaml#L57

We can use something like
```yaml
{{ .Release.Name }}-ray-head
```

Same thing is for keycloak

https://github.com/Qiskit-Extensions/quantum-serverless/blob/a98068912427586fa4162dec6734fe9ce072c507/infrastructure/helm/quantumserverless/charts/gateway/templates/deployment.yaml#L61

and site url (this is required for django + one internal function)

https://github.com/Qiskit-Extensions/quantum-serverless/blob/a98068912427586fa4162dec6734fe9ce072c507/infrastructure/helm/quantumserverless/charts/gateway/templates/deployment.yaml#L55

**Comment by akihikokuroda** [comment]
The `rayHost` is no longer used.  It should be removed.

**Comment by akihikokuroda** [comment]
The key cloak url setting depends on the setting in the keycloak section of the values.yaml file.
```
keycloak:
  fullnameOverride: "keycloak"
  service:
    ports:
      http: 31059
```

The siteHost must match the service name of the gateway.  It can be fixed to `gateway` by setting
```
gateway:
  fullnameOverride: "gateway"
```
in the value file.

**Comment by IceKhan13** [comment]
closed in https://github.com/Qiskit-Extensions/quantum-serverless/pull/940
