### ISSUE TITLE
Publish helm chart

### ISSUE THREAD

**Issue by akihikokuroda** [Qiskit-Extensions/quantum-serverless#329]
### What is the expected enhancement?
Publish the quantum serverless helm chart so that it can be installed without cloning the git repository.

- [ ] [ Setup helm repository ](https://helm.sh/docs/topics/chart_repository/#github-pages-example) or find an existing repository
- [ ] build and push the helm chart into the repository

**Comment by IceKhan13** [comment]
Duplicate of https://github.com/Qiskit-Extensions/quantum-serverless/issues/52. Let's pick either one of them and close other

**Comment by akihikokuroda** [comment]
OH, I'll close this.
