### ISSUE TITLE
Rename `Program` to `NestedProgram`

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#342]
### What is the expected enhancement?

In client rename `Program` to `NestedProgram` and related references like `get_program` to `get_nested_program`.

**Comment by agarwal-aryan** [comment]
Can you please provide the path to the files in which we can work upon?

**Comment by pacomf** [comment]
@agarwal-aryan when you have ready the contribution, be free to open a PR against our main brach :) (https://github.com/Qiskit-Extensions/quantum-serverless/pulls)

**Comment by IceKhan13** [comment]
Closed in #347
