### ISSUE TITLE
Use secret for gateway superuser credentials

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#371]
We currently define the gateway credentials for the Helm install in [`values.yaml`](https://github.com/Qiskit-Extensions/quantum-serverless/blob/9f02e40479e94128bee775d200cb33f010e79fd1/infrastructure/helm/quantumserverless/values.yaml#L30-L33). 

These are added as environmental variables for the container, but as a result anyone who can view pods in the `ray` namespace can get access to the superuser credentials:

```
$ k get po -n ray quantum-serverless-gateway-745bfd7b5f-tz4z4 -o json | jq '.spec.containers[].env'
[
  ...
  {
    "name": "DJANGO_SUPERUSER_USERNAME",
    "value": "admin"
  },
  {
    "name": "DJANGO_SUPERUSER_PASSWORD",
    "value": "passw0rd"
  },
  {
    "name": "DJANGO_SUPERUSER_EMAIL",
    "value": "admin@examplemail.io"
  }
]
```

Instead of using environmental variables, we should use a more secure method depending on the environment (for example, for Kubernetes we should use [secrets](https://kubernetes.io/docs/concepts/configuration/secret/))

**Comment by Tansito** [comment]
Adding high priority to this as @akihikokuroda suggested in #921 . With the current integration that we are doing I think it has a lot of sense to start moving this in parallel.
