### ISSUE TITLE
Should we run our apps as Knative services?

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#388]
Currently, we run a couple of standalone services as part of quantum serverless: the gateway and the repository. As these are containerized services, it _might_ be worthwhile to run them as Knative services, which would simplify the setup and provide some benefits (like autoscaling and networking) that we might want to take advantage of.

Opening this issue to explore this topic a bit...

**Comment by Tansito** [comment]
Btw and just to confirm the context, is this issue related with some of these conversations that we had?
- #306 
- https://github.com/Qiskit-Extensions/quantum-serverless/pull/381#discussion_r1153297465

**Comment by psschwei** [comment]
My main thought process here was :  
* we're deploying a number of services to Kubernetes
* Knative makes it easy to deploy services to Kubernetes
* should we think about using Knative to deploy services?

That's about as far as I've gotten :smile: 

I think this was partially motivated by some of the issues we saw in #255 and some of the Keycloak PRs. Knative _could_ help here, but there would also be some additional overhead with the knative components... so really just an open question at this point.

Knative docs for Serving (which is the component we'd use) are here: https://knative.dev/docs/serving/

**Comment by pacomf** [comment]
The only question here is... Can we reuse it outside of kubernetes? We should be much agnostic as possible... it means, we need to have the ability to deploy our stack outside of kubernetes environment... but if we consider that Knative can be great for the kubernetes deployment or whatever, we can discuss as well... but to have in mind that we need to provide the option to deploy the stack in other places (not just kubernetes)

**Comment by psschwei** [comment]
That's fair... I was assuming those parts would always run on kubernetes / openshift as part of the more general hybrid / multi cloud strategy
