### ISSUE TITLE
Cut images for release

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#406]
### What is the expected behavior?

Currently, we are releasing `nightly` images for our builds. In addition to the nightlies / latest, we should also have images for each release, i.e. `gateway:v0.0.6`, `gateway:v0.0.5`, etc. so that users can have a stable set of images to use / install.

**Comment by akihikokuroda** [comment]
I thought that [this action](https://github.com/Qiskit-Extensions/quantum-serverless/blob/main/.github/workflows/image-build-and-push.yml) does it.

**Comment by psschwei** [comment]
Looks like it's some but not others...

https://hub.docker.com/r/qiskit/quantum-serverless-gateway/tags

https://hub.docker.com/r/qiskit/quantum-serverless-notebook/tags

**Comment by psschwei** [comment]
(maybe there's no versioned gateway because the gateway wasn't part of the last release...)

**Comment by psschwei** [comment]
yeah, that seems to be it... gateway wasn't added to the CI before the last version was cut
