### ISSUE TITLE
Ray-node container image always for linux/amd64 platform 

### ISSUE THREAD

**Issue by akihikokuroda** [Qiskit-Extensions/quantum-serverless#420]
### Steps to reproduce the problem
The Ray-node container is for linux/amd64 platform when it is built on M1 MAC.

### What is the current behavior?
The image platform is always linux/amd64

### What is the expected behavior?
The image for linux/arm64 should be built when it is built on M1 Mac

**Comment by IceKhan13** [comment]
Closed in https://github.com/Qiskit-Extensions/quantum-serverless/pull/421
