### ISSUE TITLE
Tests: jupyter notebooks with examples

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#443]
### What is the expected enhancement?

Implement tests + ci for jupyter notebook with examples

**Comment by IceKhan13** [comment]
Need to discuss how this tests should run. They will be heavy as we need to run raynode + gateway to run examples.

**Comment by psschwei** [comment]
Tests were added that run the notebooks in #652 ... is there anything else we need for this one?

**Comment by psschwei** [comment]
Lazy consensus says we're good here :wink:
