### ISSUE TITLE
Running the notebooks in docs/tutorials + docs/guides

### ISSUE THREAD

**Issue by gavinking** [Qiskit-Extensions/quantum-serverless#448]
The README explains how to run the notebooks in `docs/getting_started`, and I got them working quickly. But it doesn't really explain what I need to do to run the notebooks in `docs/tutorials` and in `docs/guides`.

I tried editing `docker-compose.yml` like so:

```yaml
    volumes:
      - ./docs/tutorials:/home/jovyan/
```

And that seemed to work, but when I ran `01_quantum_serverless.ipynb`, I got a `ConnectionRefusedError`, when trying to connect with:

```python
    GatewayProvider(
        username="john",
        password="password123",
        host="http://localhost:8000/",
    )
```

I verified that there *is* a Django server running on that port, so perhaps the credentials are wrong? (Not sure.)

Anyway it would be nice if all the notebooks were visible in Jupyter by default, and could be run without needing to do any extra work.

**Comment by IceKhan13** [comment]
Hey @gavinking! Thank you for reporting this!

indeed we need to make login and passwords clearer in documentation. Login is `user` and password is `password123`. This is defined in keycloak realm config file [here](https://github.com/Qiskit-Extensions/quantum-serverless/blob/main/realm-export.json#L472). 

After minor `0.1` release in following week our priority is documentation, where we will update our tutorials and guides (and general structure of documentation).
