### ISSUE TITLE
jupyter notebook doesn't start due to a local path

### ISSUE THREAD

**Issue by draentropia** [Qiskit-Extensions/quantum-serverless#460]
### Steps to reproduce the problem
Clone the repo, navigate to the project folder, pull the docker-compose and later execute it with:
❯ VERSION=nightly docker-compose --profile full up

### What is the current behavior?
jupyter notebook doesn't starts and shows this error: 
qs-jupyter           | PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'

### What is the expected behavior?
running the qs-jupyter container without errors.

**Comment by psschwei** [comment]
I'm not able to recreate the error running from the most recent commit (https://github.com/Qiskit-Extensions/quantum-serverless/commit/93a2eb9a02f7c1f753432d6e2e7912e3e888ec2b) and pulling the images before running.

Can you post the full jupyter logs and maybe some info about your system to help debug? (OS, docker version, etc.)

**Comment by psschwei** [comment]
One thing that might help would be to delete any old jupyter image to make sure compose is running with the latest, by running something like `docker image rm qiskit/quantum-serverless-notebook:nightly-py39 --force`

**Comment by akihikokuroda** [comment]
@draentropia What is the file permission of the docs/getting_started in your local cloned project?  Can you create a file in the directory?

**Comment by draentropia** [comment]
I'd found the issue. The docker-compose file was mounting this folder in /home/jovyan (hardcoded, presumably jovyan was the last person using jupyteer container before the commit to master) instead than in $HOME. 

I changed it locally to point to my users home directory.

**Comment by IceKhan13** [comment]
About `jovyan` user https://discourse.jupyter.org/t/what-is-with-the-weird-jovyan-user/1673/3 and why it is called like that :)

**Comment by psschwei** [comment]
For reference, here's what I've got locally in the `docs/getting_started/` directory:

```
$ ll docs/getting_started/ -a
total 72
drwxr-xr-x. 9 paulschw paulschw  4096 Apr 27 10:45 .
drwxr-xr-x. 8 paulschw paulschw  4096 Apr 16 07:36 ..
-rw-r--r--. 1 paulschw paulschw  7291 Apr 27 10:45 01_intro_level_1.ipynb
-rw-r--r--. 1 paulschw paulschw 14638 Apr 27 07:50 02_intro_level_2.ipynb
-rw-r--r--. 1 paulschw paulschw  7905 Apr 27 10:34 03_intro_level_3.ipynb
drwxr-xr-x. 7 paulschw users     4096 Apr 13 16:28 .cache
drwxr-xr-x. 3 paulschw users     4096 Apr 10 11:28 .config
-rw-r--r--. 1 paulschw paulschw    31 Mar 22 08:31 index.rst
drwxr-xr-x. 2 paulschw users     4096 Apr 27 10:41 .ipynb_checkpoints
drwxr-xr-x. 3 paulschw users     4096 Apr  4 09:50 .ipython
drwxr-xr-x. 3 paulschw users     4096 Apr  4 09:50 .jupyter
drwxr-xr-x. 3 paulschw users     4096 Mar 27 15:57 .local
drwxr-xr-x. 3 paulschw paulschw  4096 Apr 27 10:41 source_files
```

anything in the `users` group is specific to my runs of the notebooks locally (and also isn't [tracked by git](https://github.com/Qiskit-Extensions/quantum-serverless/tree/2f8cd11e2fd41ddef140e46fd94db84ac8a2c50e/docs/getting_started))... wonder if there's something simple we could do like configuring jupyter to write to a tmpdir to avoid issues like this in the future?

**Comment by IceKhan13** [comment]
I think we actually should not mount directory. Reason why jupyter is in docker-compose is only to showcase tutorials. We are building image with all tutorials, guides and getting stated tutorials already in, so we do not need to mount anything.

**Comment by psschwei** [comment]
>  we actually should not mount directory

Even better :smile:
