### ISSUE TITLE
Working with persistent storage

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#463]
### What is the expected behavior?

During program execution as a user I want to be able to save files in some kind of persistent storage allocated for my user specifically. 

As a user I might need it for:
- saving large job results
- saving checkpoints for long running jobs / variational workloads
- accessing previously saved files

Notes:
- think of s3

**Comment by pacomf** [comment]
Remember enable the redis possibility, to work with cache storage as well (the state service but through gateway to protect data between users, something like each key sent by users, add the userID like prefix to ensure that other users cant access to these keys...

We should have 2 kind of storage:
- Cache storage, to share data between tasks or store small content
- Persistent storage, to store checkpoint states or more large content

**Comment by psschwei** [comment]
I can tackle this one.

I'd lean towards configuring storage via the infrastructure rather than the SDK (i.e. via PVCs in Kubernetes over a `write_to_s3()` function call from the client), so it might make sense to wait for this until #423 is in...

**Comment by pacomf** [comment]
We need to take care to protect the access to the information between users, without expose any possible interface to get data from other users, it doesnt matter than users are from the same installation

**Comment by psschwei** [comment]
On the cache vs. persistent storage, how would we differentiate which one is used? Or would that be something for the users to decide? If the latter, perhaps we should start simple with just s3 and then introduce redis or something similar down the line if/when there's a big demand for it...

**Comment by psschwei** [comment]
xref IBM COS PVC instructions: https://cloud.ibm.com/docs/containers?topic=containers-storage_cos_apps

**Comment by pacomf** [comment]
Yeah! Exactly, let’s start with S3

**Comment by psschwei** [comment]
Well... looks like PVCs are implemented in Kuberay yet: https://github.com/ray-project/kuberay/blob/f6a172f3d7e44d4ee22bd058f2c33a69601c39c2/apiserver/pkg/util/cluster.go#L387

There's an [open issue](https://github.com/ray-project/kuberay/issues/1087) , but no clue on when it will land... that's ... _not ideal_ :frowning:

**Comment by psschwei** [comment]
@pacomf by when do we need a persistent storage solution to land?

**Comment by pacomf** [comment]
Probably before July, so maybe we need to start with our own solution, at least for the moment, @IceKhan13 what do you think?

**Comment by psschwei** [comment]
(another choice is we submit a patch to add PVC support... long-term, that may end up being less overall work)

**Comment by psschwei** [comment]
I've got a PR open for PVC support

**Comment by psschwei** [comment]
PVC support has merged into kuberay. 

@IceKhan13 we should find some time to chat on Wednesday. I have ideas 😎

**Comment by IceKhan13** [comment]
@psschwei let's do it!

**Comment by IceKhan13** [comment]
@psschwei I'm jumping on attaching PVC to workers in https://github.com/Qiskit-Extensions/quantum-serverless/issues/676 as Aki's PR is merged now https://github.com/Qiskit-Extensions/quantum-serverless/pull/670

**Comment by psschwei** [comment]
> @psschwei I'm jumping on attaching PVC to workers in #676 as Aki's PR is merged now #670. FYI :)

Will that complete this issue, or are there other things we still need to do?

**Comment by IceKhan13** [comment]
I think it should

**Comment by psschwei** [comment]
This should be finished now that #676 merged, so closing this one out
