### ISSUE TITLE
Infrastructure: improve default cluster configuration

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#471]
### What is the expected enhancement?

Infrastructure: improve default cluster configuration

Currently default cluster that is created has 1 head node with 2 cpu 2 Gb mem + 1 worker with 1 cpu 1 Gb mem.
This configuration is faulty as it is causing memory overflow once you start more than 1 parallel task. 

Todos:
- create cluster template with node types with at least 2 cpu 2 gb mem
- maybe work out couple of popular configuration keeping in mind workloads we have

**Comment by psschwei** [comment]
As part of this, would be good to come up with a set of minimum requirements for running on a cluster (min k8s version, min cpu, min memory, etc.)

For templates, we can use IKS/AWS node sizes as a rough guide on what options we might want to use

**Comment by Tansito** [comment]
@IceKhan13 with the introduction of `rayclustertemplate` for the deployment of a new cluster by `gateway` do you think we can close this issue? Probably after the tests with users we are going to need to review configurations again but let me know.

**Comment by IceKhan13** [comment]
oh, yes, we can close this as it is not relevant anymore :)
