### ISSUE TITLE
Renaming the kubernetes namespace to `quantum-serverless`

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#498]
### What is the expected enhancement?

Currently, our helm chart installs to the `ray` namespace. However, our project is called `quantum-serverless`, so this could be confusing to users / cluster admins.

Perhaps we should rename the namespace to `quantum-serverless`? 

If we do, we should also remove the `quantum-serverless-` prefix from most components, as it would be redundant.

(`quantum-serverless` seems like the obvious name to use here, but also open to another, less-obvious one)

/cc @IceKhan13 @pacomf @Tansito @akihikokuroda

**Comment by Tansito** [comment]
I don't know if left that referencie un the documentation but yeah, from #447 for example I'm assuming quantum-serverless as the namespace
