### ISSUE TITLE
Docs: improvements in docs

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#511]
### What is the expected enhancement?

Documentation website: https://qiskit-extensions.github.io/quantum-serverless/

Incorporate feedback on documentation:

- **README**
   -“Remote execution: Quantum Serverless also provides asynchronous remote job execution, making it ideal for long-running scripts or jobs that you want to run somewhere and retrieve the results later. This means that you can offload compute-intensive tasks to a remote system and receive the results when they are ready.” --> I think here we need to mention “Programs” specifically as what enables simple remote execution.
- **Quickstart**
  - we should say at the top of this page, that the instructions are for a local install. But if they want to run on remote resources they can either:
    - 1. configure their own (link to the detailed docs on that)
    - 2. or ask provider / devops team

- **tutorial: "Running a program remotely"**
  -in this tutorial and in the others, what if in section “Running the Program”, we show how to set up the Program object first, and then show how to set up QuantumServerless to run that Program?
  - text: “As result of run call we get” --> method is “run_program”
  - to keep this first tutorial as simple as possible, what if we don’t print logs, but instead save the quasi dist to results. And show how to retrieve the results. Then, in the fourth tutorial (see my note below) we show how to write to and retrieve logs from a program (e.g., as interim results from some iterative process)
  - What about having a separate and short how-to on using the job_id property to fetch old jobs / results? 

- **tutorial: "Parallel Workflows in programs"**
  - “In this document, we will learn how to run distributed workflows inside a program.” add: “In this case, we will compute the quasiprobability distribution in parallel for a list of quantum circuits.”
  - since the next tutorial shows how to handle input arguments, what if we just create the list of quantumcircuits inside this program instead of passing them as inputs to the program?

- **tutorial: "Dependency management for programs"**
  - dependencies=["qiskit-experiments"] — maybe for this one we should use a specific version number just so people can see how that would work

- **Summary of first four tutorials:**
  - tutorial 1: "Running a program remotely" (no inputs or logs)
  - tutorial 2: "Running a program with a parallel workflow" (no inputs or logs)
  - tutorial 3: "Running a program with input arguments and saving to logs" (an iterative program with inputs with interim results saved to logs)
  - tutorial 4: "Running a program with dependencies" (a program that uses an external package)

- **Misc stuff**
  - there’s a mismatch in numbering between the notebook names and the program file names (e.g., 03_arguments_and_results has program_2.py)

**Comment by caleb-johnson** [comment]
Caleb's Notes (WIP):
Quickstart:
 - `run docker compose from a root of...` --> `run docker compose from the root of...`

**Comment by akihikokuroda** [comment]
What is the pre-req for the `Quickstart`?  Does the user need to clone the repository? If not, how does the user get the docker-comose.yml?
