### ISSUE TITLE
Gateway pod CrashLoopBackOff

### ISSUE THREAD

**Issue by akihikokuroda** [Qiskit-Extensions/quantum-serverless#516]
### Steps to reproduce the problem
Install quntum-middleware via helm

### What is the current behavior?
gateway pod doesn't come up
```
gateway-969d677f9-ggvdl                                    0/1     CrashLoopBackOff   9 (4m40s ago)   23m
```

### What is the expected behavior?
Gateway pod comes up succesfully

**Comment by IceKhan13** [comment]
Can you check this works https://github.com/Qiskit-Extensions/quantum-serverless/pull/447 

If it is fixing (related) then link PR to this issue

**Comment by akihikokuroda** [comment]
This doesn't happen after #447.
