### ISSUE TITLE
Enable multi-architecture image build and push in github action

### ISSUE THREAD

**Issue by akihikokuroda** [Qiskit-Extensions/quantum-serverless#523]
### What is the expected enhancement?

The build and push action builds and push container images for amd64 architecture only.  It's better to build multi-architecture images and push them in the registry.

**Comment by akihikokuroda** [comment]
We don't need to add Mac Mx notes in the getting stared guild with this.

**Comment by psschwei** [comment]
I've got this included as a step in #298 , so I'll this as part of that.

**Comment by psschwei** [comment]
Based on discussion in #558 I think it probably makes sense to not couple this to the dockerhub migration
