### ISSUE TITLE
Client + gateway: fix user error messages

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#525]
### What is the expected enhancement?

**User story**: user should not see large error messages. All errors should be handled and clear concise message should appear for user.

Currently client and gateway returns errors with bodies, which is overwhelming for users.
We need to make error handling less verbose and more specific (like: `check auth credentials`, `authentication failed` or something along those lines).

**Comment by pacomf** [comment]
We should add error codes as well to categorize the errors and have an easy way to identify and debug them.
