### ISSUE TITLE
observability setup (monitoring and logging)

### ISSUE THREAD

**Issue by akihikokuroda** [Qiskit-Extensions/quantum-serverless#538]
### What is the expected enhancement?

A simple experience of accessing logs and metrics on executed jobs

**Comment by akihikokuroda** [comment]
@IceKhan13 Where do these information come out?   Grafana console, Ray console, cli output or a new web console?

**Comment by IceKhan13** [comment]
System logs (ray cluster, gateway, repository, etc.) should be in grafana.

Ray job logs should be accessible to users. 
```python
job = serverless.run_program(...)
job.logs()
```

**Comment by akihikokuroda** [comment]
![Screenshot 2023-05-24 at 11 42 18 AM](https://github.com/Qiskit-Extensions/quantum-serverless/assets/16141898/0191799c-3e6c-4e37-90a6-05b782ffa41d)

**Comment by akihikokuroda** [comment]
@IceKhan13 The OT tracing is instrumented and most of the logs go into Prometheus.  What is missing to close this issue?

**Comment by IceKhan13** [comment]
yes, closing it! 
Thank you!
