### ISSUE TITLE
Migrate to kuberay api service

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#55]
### What is the expected enhancement?

Kuberay helm chart provides ApiService to manage ray clusters (CRUD).

We need to migrate to this helm chart and update client to work with those resources.

Issues in project:
- https://github.com/Qiskit-Extensions/quantum-serverless/issues/130
- https://github.com/Qiskit-Extensions/quantum-serverless/issues/131
- https://github.com/Qiskit-Extensions/quantum-serverless/issues/132
- https://github.com/Qiskit-Extensions/quantum-serverless/issues/133

**Comment by psschwei** [comment]
Is this one still needed? If so, I could pick it up.

**Comment by IceKhan13** [comment]
@psschwei awesome! Thank you!
We will post list of issues related to that small epic tomorrow (basically we will split this issue into list of smaller ones) :)

**Comment by psschwei** [comment]
All linked issues have been closed
