### ISSUE TITLE
Write test ensuring build is not broken

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/quantum-serverless#646]
[This file](https://github.com/Qiskit-Extensions/quantum-serverless/blob/main/docker-compose.yml#L99) is not included in the latest image releases to the ICR, but it is required in the build, so the Quickstart guide is essentially broken for all users.

Resolution of this PR includes a new test in the CICD which ensures pushes to `main` branch do not break the build.

### Steps to reproduce the problem

Run `docker compose --full up` from main branch

### What is the current behavior?
Build breaks due to missing file.

### What is the expected behavior?
Successful build

**Comment by caleb-johnson** [comment]
@psschwei FYI

**Comment by psschwei** [comment]
#652 added the build test to the CI, so going to close this one out.
