### ISSUE TITLE
Ray node image for arm64 is broken

### ISSUE THREAD

**Issue by akihikokuroda** [Qiskit-Extensions/quantum-serverless#653]
### Steps to reproduce the problem
Run "ICR | Build and Push" action

### What is the current behavior?
https://github.com/Qiskit-Extensions/quantum-serverless/actions/runs/5203085623/jobs/9385472789

### What is the expected behavior?
built without failure

**Comment by psschwei** [comment]
```
#14 209.5 Failed to build rustworkx
#14 209.5 ERROR: Could not build wheels for rustworkx, which is required to install pyproject.toml-based projects
```

@AngeloDanducci may be able to help here

**Comment by AngeloDanducci** [comment]
Seems like this may be the root cause
https://github.com/Qiskit-Extensions/quantum-serverless/actions/runs/5203085623/jobs/9385472789#step:6:1823

Not sure if it can't find the rust compiler or maybe it doesn't exist in the env for `Run "ICR | Build and Push" action`

**Comment by akihikokuroda** [comment]
I'm not sure what happed but it's working now. I close this now.
