### ISSUE TITLE
gateway-volume is not writable in Kind

### ISSUE THREAD

**Issue by akihikokuroda** [Qiskit-Extensions/quantum-serverless#664]
### Steps to reproduce the problem
Run 01_running_program in the Kind cluster

### What is the current behavior?
500 error is reported in the Gateway pod

### What is the expected behavior?
It should run without error.

**Comment by akihikokuroda** [comment]
The hostPath
```
path: "/mnt/data/tmp"
```
is not writeable by the user 1001, group 0

So far I could make this work in Kind by changing the template/pvcs.yaml

1. removing persistentVolume gateway-volume 
2. Change the `storageClassName` to `standard` in PersistentVolumeClaim gateway-claim
3. Change the `accessMode` to `ReadWriteOnce`  in PersistentVolumeClaim gateway-claim

I have to work on to make changes work on other platforms.

**Comment by psschwei** [comment]
Confirming this works for me too on Kind :partying_face:
