### ISSUE TITLE
CI fails for working_with_datasets tutorial

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/quantum-serverless#672]
### Steps to reproduce the problem
The [working_with_datasets tutorial ](https://github.com/Qiskit-Extensions/quantum-serverless/blob/main/docs/development/guides/07_working_with_datasets.ipynb) fails in CI on #652 due to some ray commands not being handled well.

### What is the current behavior?
The tutorial above can be run in a container locally, but it fails in CI. More investigation needed.

### What is the expected behavior?
Tutorial should run in CI, as it does locally

**Comment by psschwei** [comment]
The working with datasets tutorial was deleted in #980 

![image](https://github.com/Qiskit-Extensions/quantum-serverless/assets/44698588/17ab7564-2eaf-4485-afce-f1855349825a)
