### ISSUE TITLE
Use same status names than Qiskit Job for the programs

### ISSUE THREAD

**Issue by pacomf** [Qiskit-Extensions/quantum-serverless#684]
### What is the expected enhancement?

We should known names to identify the program statuses. We can adopt the Qiskit notation for Jobs: https://qiskit.org/documentation/stubs/qiskit.providers.JobStatus.html (using just the statuses that at the end it makes sense for our programs, for example, initializing or validating we can avoid them.

So we should have at least he next ones:

```
QUEUED
RUNNING
CANCELLED
DONE
ERROR
```

If we consider add more, they are welcome, because it is more useful information for the user at the end

**Comment by IceKhan13** [comment]
Closed in https://github.com/Qiskit-Extensions/quantum-serverless/pull/1062
