### ISSUE TITLE
API References are incomplete

### ISSUE THREAD

**Issue by akihikokuroda** [Qiskit-Extensions/quantum-serverless#725]
### Steps to reproduce the problem
API References- [core module](https://qiskit-extensions.github.io/quantum-serverless/apidocs/core.html) doesn't have some classes (Job, Program)

### What is the current behavior?
Some public classes are not listed in the API References

### What is the expected behavior?
All API used by the user must be documented in the API References

**Comment by akihikokuroda** [comment]
What classes and functions should be in the API Reference?  All public classes and functions or ones that we assume that the user uses?

**Comment by psschwei** [comment]
These docs are auto-generated (I think?), so I wonder if either (a) they're missing docs completely, or (b) they aren't being marked for sphinx to build docs for.

**Comment by psschwei** [comment]
I don't really know sphinx well enough to debug if either / both / none of those are true

**Comment by akihikokuroda** [comment]
The We are listing the classes and functions to be documented.  I can add them that the user use.   I wonder if we should also document some public but (probably) internal classes and functions.

**Comment by psschwei** [comment]
I guess it depends on who the docs are for. If users, then I'd only document public functions. If developers, then probably all should be documents.

punt to @IceKhan13 @pacomf for the audience question :football:

**Comment by akihikokuroda** [comment]
Here is the list of classes we have now:
```
exception.py QuantumServerlessException(Exception)
quantum_serverless.py QuantumServerless:

core/provider.py ComputeResource
core/provider.py Provider(JsonSerializable):
core/provider.py KuberayProvider(Provider):
core/provider.py GatewayProvider(Provider):
core/events.py ExecutionMessage:
core/events.py EventHandler(ABC):
core/events.py RedisEventHandler(EventHandler):
core/job.py BaseJobClient:
core/job.py RayJobClient(BaseJobClient):
core/job.py GatewayJobClient(BaseJobClient):
core/job.py Job:
core/program.py Program:
core/program.py ProgramStorage(ABC):
core/program.py ProgramRepository(ProgramStorage):
core/state.py StateHandler(ABC):
core/state.py RedisStateHandler(StateHandler):
core/decorators.py Target(JsonSerializable):
core/decorators.py CircuitMeta:

utils/storage.py BaseStorage:
utils/storage.py S3Storage(BaseStorage):
utils/errors.py ErrorCodes:
utils/json.py JsonSerializable(ABC):

serializers/program_serializers.py QiskitObjectsEncoder(RuntimeEncoder):
serializers/program_serializers.py QiskitObjectsDecoder(RuntimeDecoder):

visualizaiton/widget.py Widget:
```

**Comment by IceKhan13** [comment]
Let's expose everything to sphinx. Api docs does not have them due to we forgot to add them to docstrings in `__init__` files of modules, which are used by sphinx to compile docs.
