### ISSUE TITLE
Infrastructure: ray cluster image caching

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#728]
### What is the expected enhancement?

Currently when we create ray cluster for the first time (and when cache is outdates) kuberentes is starting to fetch >2Gb image, which is taking roughly 90 seconds, which is not ideal. We need to think of a way how to cache docker images to speed up process.

**Comment by psschwei** [comment]
You could do something like this when installing a new release: https://jacobtomlinson.dev/posts/2023/quick-and-dirty-way-to-pre-pull-container-images-on-kubernetes/

There's also a few options in the "Speed Up Image Pulls" section of this blog that we might want to look into: https://developer.ibm.com/articles/reducing-cold-start-times-in-knative/

**Comment by akihikokuroda** [comment]
This may worth to look at https://github.com/che-incubator/kubernetes-image-puller

**Comment by akihikokuroda** [comment]
It is simple and works well for me.  

1. clone the [repo](https://github.com/che-incubator/kubernetes-image-puller).
1. edit values.yaml file in `kubernetes-image-puller/deploy/helm/`
1. install it by following [this](https://github.com/che-incubator/kubernetes-image-puller#installation---helm)

Edited values.yaml file contents
```
deploymentName: kubernetes-image-puller
image: 
  repository: quay.io/eclipse/kubernetes-image-puller
  tag: next
serviceAccount:
  name: k8s-image-puller
configMap:
  name: k8s-image-puller
  images: >
    ray-node=icr.io/quantum-public/quantum-serverless-ray-node:0.2.1-py39;
    kubectl=alpine/k8s:1.27.3;
    openssl=registry.access.redhat.com/ubi8/openssl:8.8-3;
  cachingIntervalHours: 1
  cachingMemoryRequest: "10Mi"
  cachingMemoryLimit: "20Mi"
  cachingCpuRequest: ".05"
  cachingCpuLimit: ".2"
  nodeSelector: "{}"
  imagePullSecrets: ""
  affinity: "{}"
```

**Comment by psschwei** [comment]
Not sure if it matters, but the `kubernetes-image-puller` is running a deployment to run the daemonset to prepull the nodes (so it's adding an extra layer vs. just deploying a daemonset).

**Comment by akihikokuroda** [comment]
I assume that it takes care of creating the daemonset in each kubernetes node.
