### ISSUE TITLE
Update AWS terraform configuration

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#761]
### What is the expected behavior?

From #760 we discovered that we have an outdated configuration in AWS terraform files.

I see two approaches that we can take with:
- Delete the entire configuration. We are not using it and if it's needed we can recover it later on.
- Update the configuration removing the package from it.

**Comment by psschwei** [comment]
Delete it

**Comment by IceKhan13** [comment]
delete! :)
