### ISSUE TITLE
Gateway: whenever JobSubmission client is used set retry logic.

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#768]
### What is the current behavior?

If cluster is not available for some reason job is failing in an update status loop.

### What is the expected behavior?

client to connect to cluster should have retry logic to accommodate for cases when cluster is not yet available.

**Comment by IceKhan13** [comment]
Probably it make sense to create a function wrapper for jobclient with retry logic since we are using it in multiple places.

**Comment by psschwei** [comment]
Not sure how difficult they would be to write, but we should probably try adding tests for these types of scenarios

**Comment by IceKhan13** [comment]
yes, I'm trying to carve out some time to boost test coverage for a project. It should not be that difficult. Hopefully in a week or so we have more time :)

**Comment by Tansito** [comment]
> retry logic since we are using it in multiple places

Yeah, I have the feeling that we are implementing a lot of retries in different places. Maybe something that we should start reviewing? Sounds relatively weird. Maybe it's normal until we can implement some kind of watchers or something.

**Comment by IceKhan13** [comment]
Closed in https://github.com/Qiskit-Extensions/quantum-serverless/pull/814
