### ISSUE TITLE
ICR | build and push failing

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#771]
### Steps to reproduce the problem

Execute ICR | build and push action

### What is the current behavior?

ICR | build and push action fails
https://github.com/Qiskit-Extensions/quantum-serverless/actions/runs/5541059240/jobs/10113961001

### What is the expected behavior?

The action must finish with success

**Comment by psschwei** [comment]
> ERROR: Could not install packages due to an OSError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

Might have just been a temporary failure... I'll rekick the job and see what happens.

**Comment by psschwei** [comment]
Build succeeded, so I think we're good to go :tada:
