### ISSUE TITLE
Ray cluster: TLS is blocking workers to join cluster

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#776]
### Steps to reproduce the problem

Deploy ray cluster with tls enabled

### What is the current behavior?

Workers are handing in non-ready status on `wait for GCS to be ready;`

In init container `wait-gcs-ready`

This check is always failing
>       until ray health-check --address cluster-user-994c3d3c-head-svc.quantum-serverless.svc.cluster.local:6379 > /dev/null 2>&1; do echo wait for GCS to be ready; sleep 5; done

Therefore workers cannot connect to head node a.k.a join cluster.

### What is the expected behavior?

Workers should be able to join cluster with TLS enabled

**Comment by IceKhan13** [comment]
@akihikokuroda I'm fighting with this today and have no progress. 
When TLS is turned off everything works fine.

**Comment by akihikokuroda** [comment]
@IceKhan13 I'll take a look.

**Comment by psschwei** [comment]
This is happening on IKS, so there may be something unique to that environment

**Comment by IceKhan13** [comment]
I also reproduced it in rancher desktop

**Comment by psschwei** [comment]
Well, then, nevermind :laughing:

**Comment by akihikokuroda** [comment]
It may be related to the IP address associated to the certificate.  I'm looking..
