### ISSUE TITLE
Rename quantumserverless to quantum-serverless

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#780]
### What is the expected behavior?

Due to not standardize our naming conventions we are generating errors like: #779 . I want to start introducing some conventions into this and use it along the code. My proposal is:
- quantum-serverless
- QuantumServerless

For those places where we require to reference the project. And this development should pontentially fix #779 .

**Comment by Tansito** [comment]
Opinions @IceKhan13 , @psschwei , @akihikokuroda ?

**Comment by Tansito** [comment]
I don't have an opinion yet for use cases like: `qs-observability`.

**Comment by psschwei** [comment]
+1 for using the hyphen whenever possible.

**Comment by psschwei** [comment]
@Tansito would`QuantumServerless` mainly be for use in the python code (which if I remember prefers camelCase over hyphens)?

re: `qs-observability` -- I tried to keep it short, but also add some type of distinguisher (as I can imagine there's a bunch of helm charts called `observability` out there)

**Comment by Tansito** [comment]
It's the main use case in what I was thinking yes, but I don't discard that we could find other ones. But those two possibilities are the most typicall ones I would think.

About the `qs-observability` yeah. When I saw the PR I couldn't think in a better naming either. I'm fine if we consider `qs` as the "official" shorter name, for example 🤷‍♂️
