### ISSUE TITLE
ICR build & push error

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#803]
### Steps to reproduce the problem

URL to the problem: https://github.com/Qiskit-Extensions/quantum-serverless/actions/runs/5609445045/jobs/10263679028#step:6:3405

### What is the current behavior?

I couldn't reproduce it locally but it seems that the ARM image is failing. I test the `pip install` and the `docker-build` in my computer (an Intel) and everything compiled successfully.

### What is the expected behavior?

We should be able to build and push the images without problems.

**Comment by Tansito** [comment]
@akihikokuroda I think we will need your help here 🙏

**Comment by akihikokuroda** [comment]
I opened an https://github.com/Qiskit/qiskit-terra/issues/10453 in qiskit-terra

**Comment by akihikokuroda** [comment]
There is some time gap (for now 6 hours+) between the qiskit-terra release and the download file build.  We can also work around this by adding `--only-binary=qiskit-terra` option in the `RUN pip install . --no-cache-dir --only-binary=qiskit-terra &&\` line of the Dockerfile.
