### ISSUE TITLE
Pin versions

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#806]
### What is the expected enhancement?

As the project grows we should start to stabilize the project. We found errors like #803 or #733 where pin versions can help us to prevent problems so I would like to propose start pinning versions in all the projects that we manage.

**Comment by psschwei** [comment]
Makes sense. I assume the bot will still autoupdate pinned dependencies if they're pinned?

**Comment by Tansito** [comment]
I'm not sure but I want to assume that too. Something that we will need to review 😂

**Comment by Tansito** [comment]
WIth #901 this could potentially not needed so closing by now.
