### ISSUE TITLE
Add a stable branch for building docs

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/quantum-serverless#812]
The serverless docs say they reference the latest version released to pip, as they draw the version # from that release; however, the docs are currently built from the `main` branch, which means the docs do not reflect the version they say they do.

It would probably be better to have a stable branch from which to build the docs

**Comment by psschwei** [comment]
In other projects, we've cut branches for each minor release (e.g. v0.2, v0.3, etc.) and then cherrypicked patches in if we needed to do a dot release. Looking at qiskit-terra, that seems to be how they do it as well.

**Comment by psschwei** [comment]
There will probably be a non-trivial amount of updates needed to the CI (which isn't to say we shouldn't do it, just that it might require some thinking around how to implement it)

**Comment by caleb-johnson** [comment]
OK cool, I was just about to ping you to see what you thought. It seems you have this covered for now, should I close this issue?

**Comment by psschwei** [comment]
I'd leave it open -- it's something that still needs to be implemented, so this gives us a nice place to track/discuss.

**Comment by Tansito** [comment]
Not 100% directly related but today I started with #764 so we can think in something similar

**Comment by psschwei** [comment]
Another option might be to move the docs to their own repo

**Comment by Tansito** [comment]
I would not disagree with that option. It would be my preferred one.

**Comment by psschwei** [comment]
Sounds like the solution is to move to a new repo (xref #1166), so we can probably close this one.

**Comment by IceKhan13** [comment]
I think so. Closing
