### ISSUE TITLE
Increase request payload size

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#818]
### What is the expected enhancement?

Currently maximum size of uploaded file is set to ~2 mb (which is looks like default for nginx) which is limitation for users as artifact from uploaded programs might have large artifacts.

We need to allow users to upload larger artifact files (around 50 mb).

Probably it is need to be configured in deployment nginx

**Comment by Tansito** [comment]
If I remember correctly there was a label to modify the nginx, I will take a look. Thanks Iskandar!

**Comment by psschwei** [comment]
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size

or

https://cloud.ibm.com/docs/containers?topic=containers-comm-ingress-annotations#client-request-bodysize
