### ISSUE TITLE
Make it easier for users to navigate to the repository from the docs webpage

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/quantum-serverless#820]
It would be nice to *only* link to the documentation webpage when sharing this tool, rather than the docs+repository, but there is no clear way for users to navigate to the code repository from the docs. Create an easier way for users to navigate to the repo from the docs.

**Comment by psschwei** [comment]
There's currently a link to the repo on the main landing page (as an aside, been using KDE for _years_ and just today learned that the screenshot tool has a way to add annotations...)

![image](https://github.com/Qiskit-Extensions/quantum-serverless/assets/44698588/24b3442a-96d7-4962-b54e-ef6aa26006d4)

**Comment by IceKhan13** [comment]
There is also an issue https://github.com/Qiskit/qiskit_sphinx_theme/issues/568 which is intended to add some kind of a visible link on top/side/bottom of a page for easier navigation

**Comment by IceKhan13** [comment]
P.S

Yellow arrows are fire!

**Comment by psschwei** [comment]
Given that there's an upstream issue for this and we have a link on the main page, are we good to close this one @caleb-johnson ?

**Comment by caleb-johnson** [comment]
Fixed by #481
