### ISSUE TITLE
Infra: OT tracing throughout entire stack

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#841]
### What is the expected behavior?

Currently we have setup to OT within `Program`, which trace through tasks or a job.

What we need is ability to trace request from client -> gateway -> ray cluster -> job and tasks (we have that now).

**Comment by akihikokuroda** [comment]
I'll take a look.

**Comment by psschwei** [comment]
I think you should be able to view OT metrics via prometheus (there's some discussion of it in #280 )

**Comment by akihikokuroda** [comment]
@psschwei That's right but the distributed tracing doesn't go there.  We probably need something for it.

**Comment by akihikokuroda** [comment]
I finally can see the tracing entries of the `program` locally now.  I'll start working for the additional components.

**Comment by akihikokuroda** [comment]
![Screenshot 2023-08-17 at 11 33 36 AM](https://github.com/Qiskit-Extensions/quantum-serverless/assets/16141898/9cd61048-1f6a-40e2-af61-a7d557da3d60)
