### ISSUE TITLE
Gateway: do not delete `ComputeResource` on job update, deactivate instead

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#842]
### What is the expected enhancement?

Gateway: do not delete `ComputeResource` on job update, deactivate instead.

This will allow us to keep information about program association to specific compute resource.

**Comment by akihikokuroda** [comment]
Does the ComputeResource remain for ever?

**Comment by IceKhan13** [comment]
@akihikokuroda yes. 
We can later introduce TTL to remove non-active compute resources, but we will not anywhere to hit this limit any time soon :)
