### ISSUE TITLE
Gateway: when job failed and logs are empty, add clarifying message.

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#852]
### What is the expected enhancement?

When job failed and logs are empty, add clarifying message in logs that something went wrong internally. Possibly provide metadata, so user have some understanding that error is acknowledged.

**Comment by david-alber** [comment]
@IceKhan13 I would love to give this one a shot. Can you assign me pls. :)

**Comment by IceKhan13** [comment]
Thank you @david-alber ! Assigned!
