### ISSUE TITLE
Gateway: delete program artifact after job start

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#871]
### What is the expected enhancement?

Delete program artifact after job is submitted.

**Comment by psschwei** [comment]
Looks like we're already removing the temporary directory that we've used to zip up the artifact in https://github.com/Qiskit-Extensions/quantum-serverless/blob/5c9882dcfde875cfae87a2f0d92a06e207f17ab2/gateway/api/ray.py#L89-L90 

Is there another place it needs to be removed from?

**Comment by IceKhan13** [comment]
when Program model is saved artifact is also saved into "/media/..." directory. We need to remove it form there too
