### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#876]
Noticed that we have an extra two lines at the beginning of our license (https://github.com/Qiskit-Extensions/quantum-serverless/blob/cc7ae97a2a6b4a93a183f4107810e5f4832353cc/LICENSE.txt#L1-L2) and our copyright is currently listed as 2017 (https://github.com/Qiskit-Extensions/quantum-serverless/blob/cc7ae97a2a6b4a93a183f4107810e5f4832353cc/LICENSE.txt#L191) when the repo was created in 2022. 

Wondering if we should make a couple of minor updates to the LICENSE file to fix the year / remove the extra lines?
@jenglick @IceKhan13

**Comment by jenglick** [comment]
@psschwei I think those extra lines are fine since we use same as Qiskit but I believe we can update the copyright year to be `first_year, last_year` (so in our case 2022, 2023)
