### ISSUE TITLE
Default to Python 3.11

### ISSUE THREAD

**Issue by psschwei** [Qiskit-Extensions/quantum-serverless#880]
Once #879 merges and we let enough time pass that we're completely happy with the Python 3.11 builds, we should switch the default Python over to 3.11 ... we'd need to run all the tests using it, update the helm chart / docker compose, etc. 

Probably worth waiting until after the beta rolls out to make that change though.

**Comment by IceKhan13** [comment]
It's a good suggestion to wait, since I can see how a lot of libraries that users will be installing does not have support for python 3.11 :)

**Comment by psschwei** [comment]
Given that 3.11 doesn't look like it'll be in Ray anytime soon, I'm going to close this one (we can revisit if/when we're able to get #879 in)
