### ISSUE TITLE
Deprecated context usage

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit-Extensions/quantum-serverless#94]
### Steps to reproduce the problem

Run any computation within serverless context.

### What is the current behavior?

Following deprecation warning appears

```
/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/worker.py:983: UserWarning: len(ctx) is deprecated. Use len(ctx.address_info) instead.',
 '  warnings.warn("len(ctx) is deprecated. Use len(ctx.address_info) instead.")
```

### What is the expected behavior?

Should not raise deprecation warning.

### How to fix suggestions?

Remove usage of `Contex` class in type hinting for `QuantumServerless` class.

**Comment by Tansito** [comment]
I would like to take this issue to start entering in the python part 🙏

**Comment by IceKhan13** [comment]
One thing though, initial suggestion to remove `Context` type annotation is wrong. 

This warning is happening, when we are using context managers in python on `QuantumServerless` object, like:
```python
serverless = QuantumServerless()

with serverless:
    pass
```

I think reason is somewhere inside `__enter__` method is calling `len` function on context itself, which is deprecated by ray.
