### ISSUE TITLE
Filter out ray logs

### ISSUE THREAD

**Issue by Ibrahim-Shehzad** [Qiskit-Extensions/quantum-serverless#947]
### What is the expected enhancement?

Either ray logs should be filtered out by default or the user should be given the option to filter out them out. In particular, I was getting this in my logs Handshake failed with fatal error SSL_ERROR_SSL: error:1000009c:SSL routines:OPENSSL_internal:HTTP_REQUEST. and was not sure if I could ignore it. If this is something that can be safely ignored, not having it show up in the logs in the first place would be helpful.

**Comment by akihikokuroda** [comment]
closing as done by #963
