### ISSUE TITLE
Rename Provider to ServerlessProvider

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/quantum-serverless#989]
It has been suggested to renamed `Provider` to `ServerlessProvider` to avoid confusion with other providers in the Qiskit ecosystem. This issue is to discuss that topic.

**Comment by caleb-johnson** [comment]
If we are going to do a small release to include #944 , this would be another thing that would be straightforward to include -- assuming we want to go ahead with renaming this class.

**Comment by psschwei** [comment]
Is this a new change? (we initially renamed to `Provider` in  #322 )

**Comment by jenglick** [comment]
Yes, I think we should differentiate from other IBM providers -- and `ServerlessProvider` is an option we could use for now for the "default" provider option
